// GENERATED by scripts/generate-icons.mjs from the design board. Do not edit.
// Stroke set: 24x24, 1.8 px, round caps and joins (DESIGN_SYSTEM §7).
export type IconShape =
  | { tag: 'path'; d: string; strokeWidth?: number }
  | { tag: 'rect'; x: number; y: number; width: number; height: number; rx?: number; strokeWidth?: number }
  | { tag: 'circle'; cx: number; cy: number; r: number; strokeWidth?: number };

export type IconName =
  | 'alert'
  | 'arrdown'
  | 'arrow'
  | 'back'
  | 'ban'
  | 'bell'
  | 'bookmark'
  | 'building'
  | 'cal'
  | 'camera'
  | 'cards'
  | 'chart'
  | 'chat'
  | 'chdn'
  | 'check'
  | 'chev'
  | 'chup'
  | 'clock'
  | 'copy'
  | 'del'
  | 'down'
  | 'download'
  | 'edit'
  | 'eye'
  | 'flag'
  | 'food'
  | 'gear'
  | 'gift'
  | 'grid'
  | 'heart'
  | 'help'
  | 'image'
  | 'info'
  | 'lock'
  | 'mail'
  | 'minus'
  | 'more'
  | 'phone'
  | 'pin'
  | 'plus'
  | 'plussq'
  | 'poll'
  | 'qr'
  | 'quad'
  | 'refresh'
  | 'search'
  | 'send'
  | 'share'
  | 'shield'
  | 'shift'
  | 'sliders'
  | 'swap'
  | 'tag'
  | 'tool'
  | 'trash'
  | 'trend'
  | 'undo'
  | 'up'
  | 'user'
  | 'users'
  | 'wifi'
  | 'x';

export const iconData: Record<IconName, IconShape[]> = {
  "alert": [
    {
      "tag": "path",
      "d": "M12 4 2.8 19.5h18.4z"
    },
    {
      "tag": "path",
      "d": "M12 10v4.5M12 17.2v.01"
    }
  ],
  "arrdown": [
    {
      "tag": "path",
      "d": "M12 5v14M6.5 13.5 12 19l5.5-5.5"
    }
  ],
  "arrow": [
    {
      "tag": "path",
      "d": "M19.5 12H5M11 5.5 4.5 12l6.5 6.5"
    }
  ],
  "back": [
    {
      "tag": "path",
      "d": "M15 5l-7 7 7 7"
    }
  ],
  "ban": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 8.5
    },
    {
      "tag": "path",
      "d": "M6 6l12 12"
    }
  ],
  "bell": [
    {
      "tag": "path",
      "d": "M6 16.5V11a6 6 0 1 1 12 0v5.5l1.5 2h-15z"
    },
    {
      "tag": "path",
      "d": "M10 20.5a2.2 2.2 0 0 0 4 0"
    }
  ],
  "bookmark": [
    {
      "tag": "path",
      "d": "M6.5 3.5h11a1 1 0 0 1 1 1v16l-6.5-4-6.5 4v-16a1 1 0 0 1 1-1z"
    }
  ],
  "building": [
    {
      "tag": "path",
      "d": "M4 20.5h16M6 20.5V9l6-4.5L18 9v11.5M9.5 20.5v-5h5v5M9 11h.01M12 11h.01M15 11h.01"
    }
  ],
  "cal": [
    {
      "tag": "rect",
      "x": 3.5,
      "y": 5,
      "width": 17,
      "height": 15.5,
      "rx": 3
    },
    {
      "tag": "path",
      "d": "M3.5 10h17M8 3v4M16 3v4"
    }
  ],
  "camera": [
    {
      "tag": "path",
      "d": "M3.5 8.5A1.5 1.5 0 0 1 5 7h2.5l1.6-2.2h5.8L16.5 7H19a1.5 1.5 0 0 1 1.5 1.5v9.5A1.5 1.5 0 0 1 19 19.5H5A1.5 1.5 0 0 1 3.5 18z"
    },
    {
      "tag": "circle",
      "cx": 12,
      "cy": 13,
      "r": 3.4
    }
  ],
  "cards": [
    {
      "tag": "rect",
      "x": 7,
      "y": 3,
      "width": 13,
      "height": 16,
      "rx": 3
    },
    {
      "tag": "path",
      "d": "M4 7.5v10A3.5 3.5 0 0 0 7.5 21H15"
    }
  ],
  "chart": [
    {
      "tag": "path",
      "d": "M5 20V11M11 20V5M17 20v-6M3 20.5h18"
    }
  ],
  "chat": [
    {
      "tag": "path",
      "d": "M20.5 11.5a8 8 0 0 1-11.9 7l-4.1 1 1.1-3.8a8 8 0 1 1 14.9-4.2z"
    }
  ],
  "chdn": [
    {
      "tag": "path",
      "d": "M6 9.5l6 6 6-6"
    }
  ],
  "check": [
    {
      "tag": "path",
      "d": "M5 12.5l4.5 4.5L19 7"
    }
  ],
  "chev": [
    {
      "tag": "path",
      "d": "M9.5 6l6 6-6 6"
    }
  ],
  "chup": [
    {
      "tag": "path",
      "d": "M6 14.5l6-6 6 6"
    }
  ],
  "clock": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 8.5
    },
    {
      "tag": "path",
      "d": "M12 7.5V12l3 2"
    }
  ],
  "copy": [
    {
      "tag": "rect",
      "x": 8.5,
      "y": 8.5,
      "width": 12,
      "height": 12,
      "rx": 2.5
    },
    {
      "tag": "path",
      "d": "M15.5 8.5V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v7.5a2 2 0 0 0 2 2h2.5"
    }
  ],
  "del": [
    {
      "tag": "path",
      "d": "M9 5.5h11v13H9l-6-6.5z"
    },
    {
      "tag": "path",
      "d": "M12.5 9.5l4.5 4.5M17 9.5l-4.5 4.5"
    }
  ],
  "down": [
    {
      "tag": "path",
      "d": "M6.5 9.5l5.5 5.5 5.5-5.5"
    }
  ],
  "download": [
    {
      "tag": "path",
      "d": "M12 4v11M7.5 10.5 12 15l4.5-4.5M5 19.5h14"
    }
  ],
  "edit": [
    {
      "tag": "path",
      "d": "M4 20h4.5L19.2 9.3a2 2 0 0 0 0-2.8l-1.7-1.7a2 2 0 0 0-2.8 0L4 15.5z"
    },
    {
      "tag": "path",
      "d": "M13.5 6l4.5 4.5"
    }
  ],
  "eye": [
    {
      "tag": "path",
      "d": "M2.5 12S6 5.5 12 5.5 21.5 12 21.5 12 18 18.5 12 18.5 2.5 12 2.5 12z"
    },
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 3
    }
  ],
  "flag": [
    {
      "tag": "path",
      "d": "M5.5 21V4M5.5 4.5h12l-2.2 4 2.2 4h-12"
    }
  ],
  "food": [
    {
      "tag": "path",
      "d": "M7 3.5v17M4.5 3.5v5a2.5 2.5 0 0 0 5 0v-5M17 20.5V3.5c-2.2 0-3.5 2.5-3.5 6.5H17"
    }
  ],
  "gear": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 3
    },
    {
      "tag": "path",
      "d": "M19.4 13.5a7.6 7.6 0 0 0 0-3l2-1.6-2-3.4-2.4.9a7.5 7.5 0 0 0-2.6-1.5L14 2.4h-4l-.4 2.5A7.5 7.5 0 0 0 7 6.4l-2.4-.9-2 3.4 2 1.6a7.6 7.6 0 0 0 0 3l-2 1.6 2 3.4 2.4-.9a7.5 7.5 0 0 0 2.6 1.5l.4 2.5h4l.4-2.5a7.5 7.5 0 0 0 2.6-1.5l2.4.9 2-3.4z"
    }
  ],
  "gift": [
    {
      "tag": "rect",
      "x": 3.5,
      "y": 8,
      "width": 17,
      "height": 4.5,
      "rx": 1
    },
    {
      "tag": "path",
      "d": "M5 12.5V20h14v-7.5M12 8v12M12 8C10.5 4 7 3.8 7 6s2.5 2 5 2zM12 8c1.5-4 5-4.2 5-2s-2.5 2-5 2z"
    }
  ],
  "grid": [
    {
      "tag": "rect",
      "x": 4,
      "y": 4,
      "width": 6.5,
      "height": 6.5,
      "rx": 1.5
    },
    {
      "tag": "rect",
      "x": 13.5,
      "y": 4,
      "width": 6.5,
      "height": 6.5,
      "rx": 1.5
    },
    {
      "tag": "rect",
      "x": 4,
      "y": 13.5,
      "width": 6.5,
      "height": 6.5,
      "rx": 1.5
    },
    {
      "tag": "rect",
      "x": 13.5,
      "y": 13.5,
      "width": 6.5,
      "height": 6.5,
      "rx": 1.5
    }
  ],
  "heart": [
    {
      "tag": "path",
      "d": "M12 20s-7.5-4.6-7.5-10A4.3 4.3 0 0 1 12 7.4 4.3 4.3 0 0 1 19.5 10c0 5.4-7.5 10-7.5 10z"
    }
  ],
  "help": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 8.5
    },
    {
      "tag": "path",
      "d": "M9.6 9.5a2.5 2.5 0 1 1 3.4 2.3c-.6.3-1 .8-1 1.5v.5M12 16.8v.01"
    }
  ],
  "image": [
    {
      "tag": "rect",
      "x": 3.5,
      "y": 4.5,
      "width": 17,
      "height": 15,
      "rx": 3
    },
    {
      "tag": "circle",
      "cx": 9,
      "cy": 10,
      "r": 1.7
    },
    {
      "tag": "path",
      "d": "M20.5 16l-5-5-9 8.5"
    }
  ],
  "info": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 12,
      "r": 8.5
    },
    {
      "tag": "path",
      "d": "M12 11v5.5M12 7.8v.01"
    }
  ],
  "lock": [
    {
      "tag": "rect",
      "x": 5,
      "y": 10.5,
      "width": 14,
      "height": 10,
      "rx": 2.5
    },
    {
      "tag": "path",
      "d": "M8.5 10.5V7.5a3.5 3.5 0 0 1 7 0v3"
    }
  ],
  "mail": [
    {
      "tag": "rect",
      "x": 3,
      "y": 5,
      "width": 18,
      "height": 14,
      "rx": 3
    },
    {
      "tag": "path",
      "d": "M4 7l8 6 8-6"
    }
  ],
  "minus": [
    {
      "tag": "path",
      "d": "M5 12h14"
    }
  ],
  "more": [
    {
      "tag": "path",
      "d": "M5.5 12h.01M12 12h.01M18.5 12h.01",
      "strokeWidth": 3.2
    }
  ],
  "phone": [
    {
      "tag": "path",
      "d": "M5 4h3.5l1.5 4.5-2 1.3a11 11 0 0 0 6.2 6.2l1.3-2 4.5 1.5V19a1.5 1.5 0 0 1-1.6 1.5A16 16 0 0 1 3.5 5.6 1.5 1.5 0 0 1 5 4z"
    }
  ],
  "pin": [
    {
      "tag": "path",
      "d": "M12 21s7-6.1 7-11.4A7 7 0 0 0 5 9.6C5 14.9 12 21 12 21z"
    },
    {
      "tag": "circle",
      "cx": 12,
      "cy": 9.6,
      "r": 2.5
    }
  ],
  "plus": [
    {
      "tag": "path",
      "d": "M12 5v14M5 12h14"
    }
  ],
  "plussq": [
    {
      "tag": "rect",
      "x": 3.5,
      "y": 3.5,
      "width": 17,
      "height": 17,
      "rx": 5
    },
    {
      "tag": "path",
      "d": "M12 8.5v7M8.5 12h7"
    }
  ],
  "poll": [
    {
      "tag": "path",
      "d": "M5 20V10M12 20V4M19 20v-7"
    }
  ],
  "qr": [
    {
      "tag": "rect",
      "x": 4,
      "y": 4,
      "width": 6,
      "height": 6,
      "rx": 1
    },
    {
      "tag": "rect",
      "x": 14,
      "y": 4,
      "width": 6,
      "height": 6,
      "rx": 1
    },
    {
      "tag": "rect",
      "x": 4,
      "y": 14,
      "width": 6,
      "height": 6,
      "rx": 1
    },
    {
      "tag": "path",
      "d": "M14 14h2.5v2.5H14zM17.5 17.5H20V20h-2.5zM14 19.5v.5M20 14v.5"
    }
  ],
  "quad": [
    {
      "tag": "path",
      "d": "M3.5 6.5A2.5 2.5 0 0 1 6 4h8.5A2.5 2.5 0 0 1 17 6.5v5a2.5 2.5 0 0 1-2.5 2.5H9l-3.5 3v-3A2.5 2.5 0 0 1 3.5 11.5z"
    },
    {
      "tag": "path",
      "d": "M20 9.3a2 2 0 0 1 .5 1.3v5.1a2 2 0 0 1-2 2v2.8L15.3 18H11"
    }
  ],
  "refresh": [
    {
      "tag": "path",
      "d": "M20 12a8 8 0 1 1-2.3-5.7M20 4.5v5h-5"
    }
  ],
  "search": [
    {
      "tag": "circle",
      "cx": 11,
      "cy": 11,
      "r": 7
    },
    {
      "tag": "path",
      "d": "m20 20-3.8-3.8"
    }
  ],
  "send": [
    {
      "tag": "path",
      "d": "M4 11.5 20 4l-6.5 16.5-2.6-6.4z"
    }
  ],
  "share": [
    {
      "tag": "path",
      "d": "M12 3.5v11M7.5 8 12 3.5 16.5 8M7 11.5H5.5v9h13v-9H17"
    }
  ],
  "shield": [
    {
      "tag": "path",
      "d": "M12 3l7.5 3v5.5c0 4.6-3.2 8.1-7.5 9.5-4.3-1.4-7.5-4.9-7.5-9.5V6z"
    },
    {
      "tag": "path",
      "d": "M9 12l2.2 2.2L15.5 10"
    }
  ],
  "shift": [
    {
      "tag": "path",
      "d": "M12 4 4 12.5h4.5V19h7v-6.5H20z"
    }
  ],
  "sliders": [
    {
      "tag": "path",
      "d": "M4 7h9M18 7h2M4 17h3M12 17h8"
    },
    {
      "tag": "circle",
      "cx": 15.5,
      "cy": 7,
      "r": 2.3
    },
    {
      "tag": "circle",
      "cx": 9.5,
      "cy": 17,
      "r": 2.3
    }
  ],
  "swap": [
    {
      "tag": "path",
      "d": "M7.5 4 4 7.5 7.5 11M4 7.5h13M16.5 20l3.5-3.5-3.5-3.5M20 16.5H7"
    }
  ],
  "tag": [
    {
      "tag": "path",
      "d": "M3.5 12.3V4.5a1 1 0 0 1 1-1h7.8l8.7 8.7a1 1 0 0 1 0 1.4l-7.4 7.4a1 1 0 0 1-1.4 0z"
    },
    {
      "tag": "circle",
      "cx": 8,
      "cy": 8,
      "r": 1.4
    }
  ],
  "tool": [
    {
      "tag": "path",
      "d": "M14.5 6.5a4 4 0 0 0 5 5L12 19a2.1 2.1 0 0 1-3-3l7.5-7.5a4 4 0 0 1-2-2z"
    }
  ],
  "trash": [
    {
      "tag": "path",
      "d": "M4 7h16M9.5 7V4.5h5V7M6 7l1 13h10l1-13M10 11v5M14 11v5"
    }
  ],
  "trend": [
    {
      "tag": "path",
      "d": "M3.5 17l5.5-5.5 4 4 7.5-7.5M15 8h5.5v5.5"
    }
  ],
  "undo": [
    {
      "tag": "path",
      "d": "M9 7 4.5 11.5 9 16"
    },
    {
      "tag": "path",
      "d": "M4.5 11.5H14a5.5 5.5 0 0 1 0 11h-2"
    }
  ],
  "up": [
    {
      "tag": "path",
      "d": "M7.5 10.5v10h-3v-10zM7.5 10.5 11.3 3.8c1.4 0 2.5 1.1 2.2 2.6L12.8 10h5.8a2 2 0 0 1 2 2.4l-1.3 6.4a2 2 0 0 1-2 1.7H7.5"
    }
  ],
  "user": [
    {
      "tag": "circle",
      "cx": 12,
      "cy": 8,
      "r": 4
    },
    {
      "tag": "path",
      "d": "M4.5 20.5c1.3-3.6 4.2-5.5 7.5-5.5s6.2 1.9 7.5 5.5"
    }
  ],
  "users": [
    {
      "tag": "circle",
      "cx": 9,
      "cy": 8,
      "r": 3.5
    },
    {
      "tag": "path",
      "d": "M2.5 19.5c.8-3 3.3-4.8 6.5-4.8s5.7 1.8 6.5 4.8M16 4.7a3.5 3.5 0 0 1 0 6.6M17.8 14.9c1.9.6 3.2 2.1 3.7 4.6"
    }
  ],
  "wifi": [
    {
      "tag": "path",
      "d": "M2.5 9a14 14 0 0 1 19 0M5.5 12.5a9.5 9.5 0 0 1 13 0M8.7 16a5 5 0 0 1 6.6 0M12 19.5h.01M3 3l18 18"
    }
  ],
  "x": [
    {
      "tag": "path",
      "d": "M6 6l12 12M18 6 6 18"
    }
  ]
};
