#!/usr/bin/env bash
# One-shot Supabase STAGING setup (OWNER_TODO 1, 3, 5, 8, 9; RELEASE §1).
#   bash scripts/deploy/staging-supabase.command
# Safe to re-run: it finds the existing project and only fills in what's missing.
#
# What it does, all from the Supabase CLI (free plan, $0):
#   1. logs in (browser), finds or creates the project `onlyswap-staging`
#   2. links the repo, applies every migration, pushes auth settings
#      (hooks, 6-digit code emails, MFA, Gmail SMTP when given)
#   3. creates the Vault secrets the database needs (random values, never shown)
#   4. sets the Edge Function secrets and deploys the functions
#   5. writes public values (URL, publishable key) to .env.staging (git-ignored)
# Secrets: the database password and random keys are generated here and kept in
# the macOS Keychain. The Gmail app password is typed at a hidden prompt. None
# of them is printed, logged or committed.
cd "$(dirname "$0")/../.." || exit 1
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
set -o pipefail
NAME=onlyswap-staging
REGION=us-east-1
SITE_URL=https://onlyswap.pages.dev
STATE=.env.staging
LOG=staging-supabase.log
: > "$LOG"
SB() { pnpm -s supabase "$@"; }
say() { echo; echo "== $*" | tee -a "$LOG"; }
die() { echo "STOPPED: $*" | tee -a "$LOG"; exit 1; }
kc_get() { security find-generic-password -a "$NAME" -s "$1" -w 2>/dev/null; }
kc_set() { security add-generic-password -U -a "$NAME" -s "$1" -w "$2" >/dev/null; }
json() { node -e "let s='';process.stdin.on('data',d=>s+=d).on('end',()=>{const j=JSON.parse(s);$1})"; }

say "1/7 Supabase login"
SB projects list -o json >/dev/null 2>&1 || SB login || die "login failed"

say "2/7 Find or create $NAME"
REF=$(SB projects list -o json | json "const p=(Array.isArray(j)?j:[]).find(p=>p.name==='$NAME');console.log(p?(p.ref||p.id):'')")
PW=$(kc_get onlyswap-db-password)
if [ -z "$REF" ]; then
  ORG=$(SB orgs list -o json | json "console.log((j[0]||{}).id||'')")
  [ -n "$ORG" ] || die "no Supabase organization found; create one at supabase.com/dashboard"
  [ -n "$PW" ] || { PW=$(openssl rand -hex 24); kc_set onlyswap-db-password "$PW"; }
  SB projects create "$NAME" --org-id "$ORG" --db-password "$PW" --region "$REGION" 2>&1 \
    | grep -v -i password | tee -a "$LOG" || die "create failed (free plan allows 2 active projects: pause an old one)"
  REF=$(SB projects list -o json | json "const p=j.find(p=>p.name==='$NAME');console.log(p?(p.ref||p.id):'')")
fi
[ -n "$REF" ] || die "could not find the project ref"
echo "project ref: $REF (not a secret)" | tee -a "$LOG"
if [ -z "$PW" ]; then
  read -rsp "Database password for $NAME (hidden; reset it in Dashboard > Database if lost): " PW; echo
  kc_set onlyswap-db-password "$PW"
fi
printf 'waiting for the project to be ready'
for _ in $(seq 1 90); do
  ST=$(SB projects list -o json | json "const p=j.find(p=>(p.ref||p.id)==='$REF');console.log(p?p.status:'')")
  [ "$ST" = "ACTIVE_HEALTHY" ] && break
  printf '.'; sleep 10
done
echo " $ST" | tee -a "$LOG"
[ "$ST" = "ACTIVE_HEALTHY" ] || die "project not healthy yet; run this again in a few minutes"
export SUPABASE_DB_PASSWORD="$PW"

say "3/7 Link and apply migrations"
SB link --project-ref "$REF" 2>&1 | tee -a "$LOG" || die "link failed"
SB db push --include-all --yes 2>&1 | tee -a "$LOG" || die "db push failed"

say "4/7 Email sender (Gmail) for login codes"
GMAIL_USER=$(kc_get onlyswap-gmail-user)
GMAIL_PASS=$(kc_get onlyswap-gmail-app-password)
if [ -z "$GMAIL_PASS" ]; then
  echo "Login codes need a sender. Use a Gmail with 2-Step Verification and an app password"
  echo "(myaccount.google.com/apppasswords, name it OnlySwap). Press Enter to skip for now."
  read -rp "Sender Gmail address: " GMAIL_USER
  if [ -n "$GMAIL_USER" ]; then
    read -rsp "Gmail app password, 16 letters (hidden): " GMAIL_PASS; echo
    GMAIL_PASS=$(printf %s "$GMAIL_PASS" | tr -d ' ')
    kc_set onlyswap-gmail-user "$GMAIL_USER"; kc_set onlyswap-gmail-app-password "$GMAIL_PASS"
  fi
fi
SUPPORT=$(kc_get onlyswap-support-inbox)
if [ -z "$SUPPORT" ]; then
  read -rp "Support inbox (where help requests go, Enter = sender Gmail): " SUPPORT
  SUPPORT=${SUPPORT:-$GMAIL_USER}
  [ -n "$SUPPORT" ] && kc_set onlyswap-support-inbox "$SUPPORT"
fi

say "5/7 Auth settings (hooks, code emails, MFA)"
# Regenerate the staging block in config.toml between the markers.
node - "$REF" "$SITE_URL" "$GMAIL_USER" <<'NODE'
const fs = require('fs');
const [ref, site, gmail] = process.argv.slice(2);
const file = 'supabase/config.toml';
const start = '# >>> remotes.staging (generated by scripts/deploy/staging-supabase.command)';
const end = '# <<< remotes.staging';
let toml = fs.readFileSync(file, 'utf8');
const i = toml.indexOf(start);
if (i >= 0) toml = toml.slice(0, i).trimEnd() + '\n' + toml.slice(toml.indexOf(end) + end.length).trimStart();
const smtp = gmail
  ? `\n[remotes.staging.auth.email.smtp]\nenabled = true\nhost = "smtp.gmail.com"\nport = 465\nuser = "${gmail}"\npass = "env(STAGING_SMTP_PASS)"\nadmin_email = "${gmail}"\nsender_name = "OnlySwap"\n`
  : '';
toml = `${toml.trimEnd()}\n\n${start}\n[remotes.staging]\nproject_id = "${ref}"\n\n[remotes.staging.auth]\nsite_url = "${site}"\nadditional_redirect_urls = ["${site}"]\n${smtp}${end}\n`;
fs.writeFileSync(file, toml);
NODE
STAGING_SMTP_PASS="$GMAIL_PASS" SB config push --project-ref "$REF" --yes 2>&1 | tee -a "$LOG" || die "config push failed"

say "6/7 Vault secrets and function secrets"
KEYS=$(SB projects api-keys --project-ref "$REF" --reveal -o json) || die "could not read API keys"
PUBLISHABLE=$(printf %s "$KEYS" | json "const k=j.find(k=>(k.api_key||'').startsWith('sb_publishable_'))||j.find(k=>k.name==='anon');console.log(k?k.api_key:'')")
[ -n "$PUBLISHABLE" ] || die "publishable key missing"
# The database calls internal functions with Vault service_role_key; the
# functions accept it as INTERNAL_FUNCTION_KEY. A random key works whether or
# not the project still has legacy JWT keys.
for k in email_hash_pepper waitlist_email_key media_signing_key internal_function_key; do
  [ -n "$(kc_get "onlyswap-vault-$k")" ] || kc_set "onlyswap-vault-$k" "$(openssl rand -hex 32)"
done
vault_sql() { # name value mode(keep|replace)
  if [ "$3" = keep ]; then
    echo "select vault.create_secret('$2', '$1') where not exists (select 1 from vault.secrets where name = '$1');"
  else
    echo "select case when exists (select 1 from vault.secrets where name = '$1') then vault.update_secret((select id from vault.secrets where name = '$1'), '$2')::text else vault.create_secret('$2', '$1')::text end;"
  fi
}
SQLF=$(mktemp); chmod 600 "$SQLF"
{
  vault_sql email_hash_pepper "$(kc_get onlyswap-vault-email_hash_pepper)" keep
  vault_sql waitlist_email_key "$(kc_get onlyswap-vault-waitlist_email_key)" keep
  vault_sql media_signing_key "$(kc_get onlyswap-vault-media_signing_key)" keep
  vault_sql functions_url "https://$REF.supabase.co/functions/v1" replace
  vault_sql service_role_key "$(kc_get onlyswap-vault-internal_function_key)" replace
  [ -n "$SUPPORT" ] && vault_sql support_inbox "$SUPPORT" replace
} > "$SQLF"
SB db query --linked -f "$SQLF" >/dev/null 2>>"$LOG"; rc=$?; rm -f "$SQLF"
[ $rc -eq 0 ] || die "vault setup failed (see $LOG)"
echo "vault: 6 secrets in place" | tee -a "$LOG"
SECF=$(mktemp); chmod 600 "$SECF"
{
  echo "APP_ENV=staging"
  echo "SITE_URL=$SITE_URL"
  echo "EMAIL_PROVIDER=gmail"
  echo "INTERNAL_FUNCTION_KEY=$(kc_get onlyswap-vault-internal_function_key)"
  # Cloudflare's published always-pass Turnstile test secret: staging only.
  echo "TURNSTILE_SECRET_KEY=1x0000000000000000000000000000000AA"
  if [ -n "$GMAIL_PASS" ]; then
    echo "GMAIL_USER=$GMAIL_USER"; echo "GMAIL_APP_PASSWORD=$GMAIL_PASS"; echo "EMAIL_FROM=OnlySwap <$GMAIL_USER>"
  fi
} > "$SECF"
SB secrets set --project-ref "$REF" --env-file "$SECF" >/dev/null 2>>"$LOG"; rc=$?; rm -f "$SECF"
[ $rc -eq 0 ] || die "function secrets failed (see $LOG)"
echo "function secrets set" | tee -a "$LOG"

say "7/7 Deploy Edge Functions"
FNS=$(ls -d supabase/functions/*/ | xargs -n1 basename | grep -v -e '^_shared$' -e '^test-inbox$' | tr '\n' ' ')
# shellcheck disable=SC2086
SB functions deploy $FNS --project-ref "$REF" --use-api 2>&1 | tee -a "$LOG" || die "functions deploy failed"

cat > "$STATE" <<EOF
# Public staging values (written by scripts/deploy/staging-supabase.command). Not secrets.
STAGING_REF=$REF
EXPO_PUBLIC_APP_ENV=staging
EXPO_PUBLIC_SUPABASE_URL=https://$REF.supabase.co
EXPO_PUBLIC_SUPABASE_ANON_KEY=$PUBLISHABLE
EXPO_PUBLIC_SITE_URL=$SITE_URL
EOF
say "Check"
echo "health: $(curl -s "https://$REF.supabase.co/functions/v1/health")" | tee -a "$LOG"
echo "auth:   $(curl -s -o /dev/null -w '%{http_code}' -H "apikey: $PUBLISHABLE" "https://$REF.supabase.co/auth/v1/settings")" | tee -a "$LOG"
echo "DONE $(date)" | tee -a "$LOG"
