#!/usr/bin/env node
// P2-TOK-01: tokens.json -> dist/unistyles.ts (app) + dist/tokens.css (site, admin).
// `--check` exits 1 when the committed dist files are stale (used in tests/CI).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'tokens.json'), 'utf8'));
const HEADER =
  '// GENERATED by packages/tokens/scripts/generate.mjs from tokens.json. Do not edit.\n';

const strip = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith('$')));

export function buildTs(t) {
  const accents = t.color.accents;
  const type = Object.fromEntries(
    Object.entries(strip(t.type)).map(([name, v]) => [
      name,
      {
        fontSize: v.size,
        fontWeight: v.weight,
        letterSpacing: Math.round(v.size * v.tracking * 100) / 100,
        lineHeight: Math.round(v.size * v.line * 100) / 100,
        ...(v.tabular ? { fontVariant: ['tabular-nums'] } : {}),
      },
    ]),
  );
  const j = (v) => JSON.stringify(v, null, 2);
  return `${HEADER}
export const palette = {
  light: ${j(t.color.light)},
  dark: ${j(t.color.dark)},
} as const;

export const accents = ${j(accents)} as const;

export type AccentName = keyof typeof accents;
export type Mode = 'light' | 'dark';

export const defaultAccent: AccentName = ${j(t.color.defaultAccent)};

export const type = ${j(type)} as const;

export type TypeVariant = keyof typeof type;

export const space = ${j(t.space)} as const;

export const radius = ${j(t.radius)} as const;

export const size = ${j(strip(t.size))} as const;

export const elevation = ${j(t.elevation)} as const;

export const motion = ${j(strip(t.motion))} as const;

export const fontScale = ${j(t.fontScale)} as const;

/** Builds one Unistyles theme: palette for the mode plus the chosen accent. */
export function makeTheme(mode: Mode, accentName: AccentName = defaultAccent) {
  const a = accents[accentName];
  return {
    mode,
    colors: {
      ...palette[mode],
      accent: a.accent,
      onAccent: mode === 'light' ? a.onAccentLight : a.onAccentDark,
    },
    type,
    space,
    radius,
    size,
    elevation,
    motion,
    fontScale,
  };
}

export type Theme = ReturnType<typeof makeTheme>;
`;
}

export function buildCss(t) {
  const vars = (o, prefix) =>
    Object.entries(o)
      .map(([k, v]) => `  --${prefix}-${k}: ${typeof v === 'number' ? `${v}px` : v};`)
      .join('\n');
  const a = t.color.accents[t.color.defaultAccent];
  const typeVars = Object.entries(strip(t.type))
    .map(
      ([k, v]) =>
        `  --type-${k}: ${v.weight} ${v.size}px/${v.line} -apple-system, system-ui, sans-serif;\n  --type-${k}-tracking: ${v.tracking}em;`,
    )
    .join('\n');
  return `/* GENERATED by packages/tokens/scripts/generate.mjs from tokens.json. Do not edit. */
:root {
${vars(t.color.light, 'color')}
  --color-accent: ${a.accent};
  --color-onAccent: ${a.onAccentLight};
${vars(t.space, 'space')}
${vars(t.radius, 'radius')}
${typeVars}
  --motion-tap: ${t.motion.tap.duration}ms;
  --motion-fade: ${t.motion.fade.duration}ms;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${vars(t.color.dark, 'color').replace(/^ {2}/gm, '    ')}
    --color-onAccent: ${a.onAccentDark};
  }
}

:root[data-theme='dark'] {
${vars(t.color.dark, 'color')}
  --color-onAccent: ${a.onAccentDark};
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-tap: 0ms;
  }
}
`;
}

const outputs = { 'dist/unistyles.ts': buildTs(tokens), 'dist/tokens.css': buildCss(tokens) };

if (process.argv.includes('--check')) {
  const stale = Object.entries(outputs).filter(([f, c]) => {
    try {
      return readFileSync(join(root, f), 'utf8') !== c;
    } catch {
      return true;
    }
  });
  if (stale.length) {
    console.error(
      `stale generated files: ${stale.map(([f]) => f).join(', ')}. Run pnpm --filter @onlyswap/tokens build`,
    );
    process.exit(1);
  }
  console.log('tokens: generated files are up to date');
} else {
  mkdirSync(join(root, 'dist'), { recursive: true });
  for (const [f, c] of Object.entries(outputs)) writeFileSync(join(root, f), c);
  console.log(`tokens: wrote ${Object.keys(outputs).join(', ')}`);
}
