#!/usr/bin/env node
// Extracts the board's icon symbols (design/OS_FInal Design.html, <symbol id="i-*">)
// into apps/mobile/src/components/icons/iconData.ts (DESIGN_SYSTEM §7).
// `--check` exits 1 when the committed file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'design/OS_FInal Design.html'), 'utf8');
const out = join(root, 'apps/mobile/src/components/icons/iconData.ts');

const shapes = {};
for (const [, id, body] of html.matchAll(/<symbol[^>]*id="i-([^"]+)"[^>]*>([\s\S]*?)<\/symbol>/g)) {
  const name = id.replace(/-(\w)/g, (_, c) => c.toUpperCase());
  shapes[name] = [...body.matchAll(/<(path|rect|circle)([^>]*?)\/?>/g)].map(([, tag, attrs]) => {
    const props = Object.fromEntries(
      [...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(([, k, v]) => [
        k.replace(/-(\w)/g, (_, c) => c.toUpperCase()),
        /^-?[\d.]+$/.test(v) ? Number(v) : v,
      ]),
    );
    return { tag, ...props };
  });
}

const names = Object.keys(shapes).sort();
const content = `// GENERATED by scripts/generate-icons.mjs from the design board. Do not edit.
// Stroke set: 24x24, 1.8 px, round caps and joins (DESIGN_SYSTEM §7).
export type IconShape =
  | { tag: 'path'; d: string; strokeWidth?: number }
  | { tag: 'rect'; x: number; y: number; width: number; height: number; rx?: number; strokeWidth?: number }
  | { tag: 'circle'; cx: number; cy: number; r: number; strokeWidth?: number };

export type IconName =
${names.map((n) => `  | '${n}'`).join('\n')};

export const iconData: Record<IconName, IconShape[]> = ${JSON.stringify(Object.fromEntries(names.map((n) => [n, shapes[n]])), null, 2)};
`;

if (process.argv.includes('--check')) {
  if (readFileSync(out, 'utf8') !== content) {
    console.error('iconData.ts is stale: run node scripts/generate-icons.mjs');
    process.exit(1);
  }
  console.log(`icons: ${names.length} icons up to date`);
} else {
  writeFileSync(out, content);
  console.log(`icons: wrote ${names.length} icons`);
}
