// P14-LEGAL-01: the app bundles the same legal text as the site.
//   node scripts/sync-legal.mjs          writes apps/mobile/src/legal/generated.ts
//   node scripts/sync-legal.mjs --check  fails when the app copy is out of date (CI)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../', import.meta.url).pathname;
const src = join(root, 'apps/site/src/content/legal');
const out = join(root, 'apps/mobile/src/legal/generated.ts');

function parse(file) {
  const text = readFileSync(join(src, file), 'utf8');
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
  if (!m) throw new Error(`${file}: missing front matter`);
  const fm = Object.fromEntries(
    m[1].split('\n').map((l) => {
      const i = l.indexOf(':');
      return [
        l.slice(0, i).trim(),
        l
          .slice(i + 1)
          .trim()
          .replace(/^'(.*)'$/, '$1'),
      ];
    }),
  );
  return {
    slug: file.replace(/\.md$/, ''),
    title: fm.title,
    version: fm.version,
    order: Number(fm.order),
    body: m[2].trim(),
  };
}

const docs = readdirSync(src)
  .filter((f) => f.endsWith('.md'))
  .map(parse)
  .sort((a, b) => a.order - b.order);

const content =
  '// GENERATED by scripts/sync-legal.mjs from apps/site/src/content/legal. Do not edit.\n' +
  `export const LEGAL = ${JSON.stringify(
    Object.fromEntries(
      docs.map((d) => [d.slug, { title: d.title, version: d.version, body: d.body }]),
    ),
    null,
    2,
  )} as const;\n\n` +
  'export type LegalSlug = keyof typeof LEGAL;\n';

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    current = '';
  }
  if (current !== content) {
    console.error('legal: the app copy differs from the site. Run `node scripts/sync-legal.mjs`.');
    process.exit(1);
  }
  console.log(`legal: app and site match (${docs.length} documents)`);
} else {
  writeFileSync(out, content);
  console.log(`legal: wrote ${docs.length} documents`);
}
