-- 0100_ref_data.sql (P3-DB-11, DATA_MODEL §7, BE-15)
-- Production reference data: categories, banned words and app_config defaults.
-- Every statement is an idempotent upsert, so re-running this file changes
-- nothing. app_config defaults never overwrite a value an admin has set.

-- Categories (board D2/B17: Dorm & furniture, Textbooks, Tech with sub-categories,
-- Clothes & shoes, Kitchen, Bikes & scooters, Music; plus Sports, Decor, Other).
-- "Free stuff" is listing kind 'free', not a category.
insert into public.categories (id, slug, name, parent_id, sort) values
  (1,  'dorm-furniture',     'Dorm & furniture',  null, 10),
  (2,  'textbooks',          'Textbooks',         null, 20),
  (3,  'tech',               'Tech',              null, 30),
  (4,  'clothes-shoes',      'Clothes & shoes',   null, 40),
  (5,  'kitchen',            'Kitchen',           null, 50),
  (6,  'bikes-scooters',     'Bikes & scooters',  null, 60),
  (7,  'music',              'Music',             null, 70),
  (8,  'sports-outdoors',    'Sports & outdoors', null, 80),
  (9,  'decor',              'Decor',             null, 90),
  (99, 'other',              'Other',             null, 990),
  (31, 'tech-monitors',      'Monitors',          3,    31),
  (32, 'tech-laptops',       'Laptops',           3,    32),
  (33, 'tech-phones-tablets','Phones & tablets',  3,    33),
  (34, 'tech-audio',         'Audio',             3,    34),
  (35, 'tech-gaming',        'Gaming',            3,    35)
on conflict (id) do update
  set slug = excluded.slug, name = excluded.name, parent_id = excluded.parent_id, sort = excluded.sort
  where (public.categories.slug, public.categories.name, public.categories.parent_id, public.categories.sort)
    is distinct from (excluded.slug, excluded.name, excluded.parent_id, excluded.sort);

-- Banned words (board X25 banned items, build plan §19.5, LEG-05 pets, gift cards,
-- recalled items). Matching and normalization (lowercase, unaccent, leetspeak,
-- repeats) happen in private.check_text (P3-DB-07).
--   block  = the text is rejected with BANNED_TERM
--   review = the listing is held for review (held_review), X14
-- Scopes: listing (incl. Wanted, free, food), quad, profile, offer, rating.
-- Chat messages are never scanned (DEC 9).
insert into public.banned_words (pattern, match, scopes, action)
select v.pattern, v.match, v.scopes, v.action
from (values
  -- Alcohol, vapes, nicotine and weed
  ('alcohol','word','{listing,quad}'::text[],'block'),
  ('beer','word','{listing,quad}','block'),
  ('liquor','word','{listing,quad}','block'),
  ('vodka','word','{listing,quad}','block'),
  ('whiskey','word','{listing,quad}','block'),
  ('whisky','word','{listing,quad}','block'),
  ('tequila','word','{listing,quad}','block'),
  ('rum','word','{listing,quad}','block'),
  ('booze','word','{listing,quad}','block'),
  ('keg','word','{listing,quad}','block'),
  ('hard seltzer','phrase','{listing,quad}','block'),
  ('white claw','phrase','{listing,quad}','block'),
  ('wine','word','{listing,quad}','review'),
  ('vape','word','{listing,quad}','block'),
  ('vapes','word','{listing,quad}','block'),
  ('vape pen','phrase','{listing,quad}','block'),
  ('juul','word','{listing,quad}','block'),
  ('elf bar','phrase','{listing,quad}','block'),
  ('elfbar','word','{listing,quad}','block'),
  ('geek bar','phrase','{listing,quad}','block'),
  ('puff bar','phrase','{listing,quad}','block'),
  ('disposable vape','phrase','{listing,quad}','block'),
  ('nicotine','word','{listing,quad}','block'),
  ('zyn','word','{listing,quad}','block'),
  ('zyns','word','{listing,quad}','block'),
  ('nic pouches','phrase','{listing,quad}','block'),
  ('nicotine pouches','phrase','{listing,quad}','block'),
  ('snus','word','{listing,quad}','block'),
  ('cigarette','word','{listing,quad}','block'),
  ('cigarettes','word','{listing,quad}','block'),
  ('cigar','word','{listing,quad}','block'),
  ('cigars','word','{listing,quad}','block'),
  ('swisher','word','{listing,quad}','block'),
  ('backwoods','word','{listing,quad}','review'),
  ('hookah','word','{listing,quad}','review'),
  ('shisha','word','{listing,quad}','block'),
  ('weed','word','{listing,quad}','block'),
  ('marijuana','word','{listing,quad}','block'),
  ('cannabis','word','{listing,quad}','block'),
  ('thc','word','{listing,quad}','block'),
  ('cbd','word','{listing,quad}','block'),
  ('delta 8','phrase','{listing,quad}','block'),
  ('delta8','word','{listing,quad}','block'),
  ('thc cart','phrase','{listing,quad}','block'),
  ('thc carts','phrase','{listing,quad}','block'),
  ('dab pen','phrase','{listing,quad}','block'),
  ('wax pen','phrase','{listing,quad}','block'),
  ('edibles','word','{listing,quad}','block'),
  ('pre roll','phrase','{listing,quad}','block'),
  ('preroll','word','{listing,quad}','block'),
  ('prerolls','word','{listing,quad}','block'),
  ('kush','word','{listing,quad}','block'),
  ('bong','word','{listing,quad}','block'),
  ('rolling papers','phrase','{listing,quad}','block'),
  ('blunt','word','{listing,quad}','review'),
  ('grinder','word','{listing,quad}','review'),
  -- Medication and drugs (prescription, over the counter, supplements)
  ('adderall','word','{listing,quad,profile,offer}','block'),
  ('vyvanse','word','{listing,quad,profile,offer}','block'),
  ('ritalin','word','{listing,quad,profile,offer}','block'),
  ('xanax','word','{listing,quad,profile,offer}','block'),
  ('oxy','word','{listing,quad,profile,offer}','block'),
  ('oxycodone','word','{listing,quad,profile,offer}','block'),
  ('percocet','word','{listing,quad,profile,offer}','block'),
  ('codeine','word','{listing,quad,profile,offer}','block'),
  ('lean','word','{listing,quad}','review'),
  ('molly','word','{listing,quad}','review'),
  ('mdma','word','{listing,quad,profile,offer}','block'),
  ('ecstasy','word','{listing,quad,profile,offer}','block'),
  ('lsd','word','{listing,quad,profile,offer}','block'),
  ('shrooms','word','{listing,quad,profile,offer}','block'),
  ('psilocybin','word','{listing,quad,profile,offer}','block'),
  ('cocaine','word','{listing,quad,profile,offer}','block'),
  ('ketamine','word','{listing,quad,profile,offer}','block'),
  ('fentanyl','word','{listing,quad,profile,offer}','block'),
  ('kratom','word','{listing,quad}','block'),
  ('prescription','word','{listing,quad}','block'),
  ('pills','word','{listing,quad}','review'),
  ('steroids','word','{listing,quad}','block'),
  ('sarms','word','{listing,quad}','block'),
  ('ibuprofen','word','{listing,quad}','block'),
  ('tylenol','word','{listing,quad}','block'),
  ('advil','word','{listing,quad}','block'),
  ('melatonin','word','{listing,quad}','block'),
  ('supplements','word','{listing,quad}','review'),
  ('pre workout','phrase','{listing,quad}','review'),
  ('preworkout','word','{listing,quad}','review'),
  -- Weapons
  ('gun','word','{listing,quad}','block'),
  ('guns','word','{listing,quad}','block'),
  ('pistol','word','{listing,quad}','block'),
  ('rifle','word','{listing,quad}','block'),
  ('shotgun','word','{listing,quad}','block'),
  ('handgun','word','{listing,quad}','block'),
  ('glock','word','{listing,quad}','block'),
  ('ar15','word','{listing,quad}','block'),
  ('ar-15','phrase','{listing,quad}','block'),
  ('ammo','word','{listing,quad}','block'),
  ('ammunition','word','{listing,quad}','block'),
  ('bullets','word','{listing,quad}','block'),
  ('gun parts','phrase','{listing,quad}','block'),
  ('holster','word','{listing,quad}','block'),
  ('suppressor','word','{listing,quad}','block'),
  ('silencer','word','{listing,quad}','block'),
  ('bb gun','phrase','{listing,quad}','block'),
  ('pellet gun','phrase','{listing,quad}','block'),
  ('airsoft','word','{listing,quad}','review'),
  ('knife','word','{listing,quad}','review'),
  ('knives','word','{listing,quad}','review'),
  ('switchblade','word','{listing,quad}','block'),
  ('butterfly knife','phrase','{listing,quad}','block'),
  ('brass knuckles','phrase','{listing,quad}','block'),
  ('pepper spray','phrase','{listing,quad}','block'),
  ('mace','word','{listing,quad}','review'),
  ('taser','word','{listing,quad}','block'),
  ('stun gun','phrase','{listing,quad}','block'),
  ('crossbow','word','{listing,quad}','block'),
  ('machete','word','{listing,quad}','block'),
  ('nunchucks','word','{listing,quad}','block'),
  ('fireworks','word','{listing,quad}','block'),
  ('firecrackers','word','{listing,quad}','block'),
  ('explosives','word','{listing,quad}','block'),
  ('gunpowder','word','{listing,quad}','block'),
  -- Fakes and IDs
  ('fake id','phrase','{listing,quad,profile,offer}','block'),
  ('fake ids','phrase','{listing,quad,profile,offer}','block'),
  ('counterfeit','word','{listing,quad}','block'),
  ('replica','word','{listing,quad}','review'),
  ('1:1','phrase','{listing,quad}','review'),
  ('student id','phrase','{listing,quad}','block'),
  ('id card','phrase','{listing,quad}','block'),
  -- Tickets, meal swipes, parking (anything tied to a school account)
  ('meal swipe','phrase','{listing,quad}','block'),
  ('meal swipes','phrase','{listing,quad}','block'),
  ('dining dollars','phrase','{listing,quad}','block'),
  ('meal plan','phrase','{listing,quad}','block'),
  ('parking pass','phrase','{listing,quad}','block'),
  ('parking permit','phrase','{listing,quad}','block'),
  ('student tickets','phrase','{listing,quad}','block'),
  ('tickets','word','{listing,quad}','review'),
  -- Coursework (textbooks are fine)
  ('test bank','phrase','{listing,quad,profile,offer}','block'),
  ('testbank','word','{listing,quad,profile,offer}','block'),
  ('answer key','phrase','{listing,quad,profile,offer}','block'),
  ('answer keys','phrase','{listing,quad,profile,offer}','block'),
  ('exam answers','phrase','{listing,quad}','review'),
  ('quiz answers','phrase','{listing,quad}','review'),
  ('past exams','phrase','{listing,quad}','review'),
  ('solutions manual','phrase','{listing,quad}','review'),
  ('essay writing','phrase','{listing,quad,profile,offer}','block'),
  ('write your essay','phrase','{listing,quad,profile,offer}','block'),
  ('write your paper','phrase','{listing,quad,profile,offer}','block'),
  ('homework help','phrase','{listing,quad,profile,offer}','block'),
  ('do your homework','phrase','{listing,quad,profile,offer}','block'),
  ('take your exam','phrase','{listing,quad,profile,offer}','block'),
  -- Services and people
  ('companionship','word','{listing,quad,profile,offer,rating}','block'),
  ('escort','word','{listing,quad,profile,offer,rating}','block'),
  ('sugar daddy','phrase','{listing,quad,profile,offer,rating}','block'),
  ('sugar baby','phrase','{listing,quad,profile,offer,rating}','block'),
  ('hookup','word','{listing,quad,profile,offer}','block'),
  ('massage','word','{listing,quad}','review'),
  ('rides','word','{listing,quad}','review'),
  ('ride share','phrase','{listing,quad}','review'),
  ('tutoring','word','{listing,quad}','review'),
  -- Housing and sublets (not allowed yet)
  ('sublet','word','{listing,quad}','block'),
  ('sublease','word','{listing,quad}','block'),
  ('subletting','word','{listing,quad}','block'),
  ('lease takeover','phrase','{listing,quad}','block'),
  ('room for rent','phrase','{listing,quad}','block'),
  ('apartment for rent','phrase','{listing,quad}','block'),
  -- Pets and animals (LEG-05)
  ('puppy','word','{listing,quad}','block'),
  ('puppies','word','{listing,quad}','block'),
  ('kitten','word','{listing,quad}','block'),
  ('kittens','word','{listing,quad}','block'),
  ('rehoming','word','{listing,quad}','block'),
  ('hamster','word','{listing,quad}','block'),
  ('reptile','word','{listing,quad}','block'),
  ('parrot','word','{listing,quad}','block'),
  ('pet','word','{listing}','review'),
  -- Gift cards (LEG-05)
  ('gift card','phrase','{listing,quad}','block'),
  ('gift cards','phrase','{listing,quad}','block'),
  ('giftcard','word','{listing,quad}','block'),
  ('prepaid card','phrase','{listing,quad}','block'),
  ('store credit','phrase','{listing,quad}','review'),
  -- Recalled items (LEG-05)
  ('recalled','word','{listing,quad}','block'),
  ('recall','word','{listing}','review'),
  ('rock n play','phrase','{listing,quad}','block'),
  ('infant sleeper','phrase','{listing,quad}','block')
) as v(pattern, match, scopes, action)
where not exists (
  select 1 from public.banned_words b where b.pattern = v.pattern and b.match = v.match
);

-- app_config defaults. `do nothing`: an admin's later change always wins.
insert into public.app_config (key, value) values
  ('maintenance',          '{"enabled": false, "until": null}'::jsonb),
  ('min_version_ios',      '"1.0.0"'::jsonb),
  ('min_version_android',  '"1.0.0"'::jsonb),
  ('rules_version',        '"1"'::jsonb),
  ('quad_enabled',         'false'::jsonb),
  ('chat_photos_enabled',  'false'::jsonb)
on conflict (key) do nothing;
