/**
 * All user-facing copy for the mobile app (CLAUDE.md rule 8).
 * Voice: plain student tone, no em dashes, no emoji, verbs on buttons.
 *
 * Native permission strings live in `permissions.json` because `app.config.ts`
 * runs in plain Node at prebuild time and can only read JSON or JS.
 */

import permissionsJson from './permissions.json';

export const permissions: Readonly<{ camera: string; photos: string }> = permissionsJson;

export const tabs = {
  discover: 'Discover',
  sell: 'Sell',
  inbox: 'Inbox',
  profile: 'Profile',
} as const;

export const shell = {
  discoverTitle: 'Discover',
  sellTitle: 'Sell',
  inboxTitle: 'Inbox',
  profileTitle: 'Profile',
  comingSoon: 'This screen is being built.',
} as const;

/** Error copy keyed by ErrorCode (API §0 + client codes). */
export const errors = {
  NOT_AUTHENTICATED: 'Sign in to keep going.',
  NOT_ACTIVE: "Your account can't do that right now. Check your profile for details.",
  AGE_REQUIRED: 'Confirm you are 18 or older to keep going.',
  RULES_REQUIRED: 'Read and accept the community rules to keep going.',
  FORBIDDEN: "You don't have access to that.",
  NOT_FOUND: "We couldn't find that. It may have been removed.",
  INVALID: 'Something in the form needs a fix. Check the highlighted fields.',
  BANNED_TERM: "That text includes words that aren't allowed on OnlySwap.",
  RATE_LIMITED: "You're doing that a lot. Try again in a little while.",
  RATE_LIMITED_UNTIL: "You're doing that a lot. Try again after {time}.",
  OFFERS_PAUSED: 'Offers are paused on your account after a missed meetup.',
  LISTING_UNAVAILABLE: "This item isn't taking offers right now.",
  OFFER_NOT_PENDING: 'This offer changed. Pull to refresh.',
  ALREADY_REPORTED: "You've already reported this. We're on it.",
  ALREADY_APPEALED: "You've already sent an appeal. We'll get back to you.",
  MEETUP_WINDOW: "That can't be done at this point in the meetup.",
  CHAT_CLOSED: 'This chat is closed.',
  CHAT_BLOCKED: "You can't send messages in this chat.",
  NOT_ADMIN: 'Admins only.',
  SCHOOL_UNKNOWN: "We don't support that school email yet.",
  DOMAIN_BLOCKED: "That email domain can't be used. Use your school email.",
  AGE_BLOCKED: 'OnlySwap is for people 18 and older.',
  BANNED: 'This account has been removed from OnlySwap.',
  FEATURE_OFF: "That isn't available yet.",
  ERR_OFFLINE: "You're offline. Check your connection and try again.",
  SESSION_EXPIRED: 'Your session ended. Sign in again.',
  UNKNOWN: 'Something went wrong. Try again.',
} as const;

export const sheet = {
  close: 'Close',
  cancel: 'Cancel',
} as const;

export const toast = {
  undo: 'Undo',
} as const;

export const banner = {
  offline: "You're offline. Some things won't update until you reconnect.",
} as const;

export const photo = {
  count: '{index} / {count}',
  failed: "Photo didn't load",
  openHint: 'Opens the photo full screen',
} as const;

/** Global screen states (DESIGN_SYSTEM §10): loading, error, offline. */
export const states = {
  loading: 'Loading',
  errorTitle: "Couldn't load this",
  offlineTitle: "You're offline",
  offlineBody: 'Check your connection and try again.',
  retry: 'Try again',
} as const;

export const nav = {
  back: 'Back',
  close: 'Close',
  tabWithBadge: '{label}, {count} new',
  step: 'Step {step} of {total}',
} as const;

/** Permission primers (P2-CMP-10, board X18, X21, A12). Buttons say Continue, not Allow. */
export const primer = {
  openSettings: 'Open Settings',
  camera: {
    title: 'Take photos of your stuff',
    body: 'OnlySwap uses the camera only when you add photos to a listing or your profile. Nothing is recorded in the background.',
    cta: 'Continue',
    alternative: 'Choose from library instead',
    deniedTitle: 'Camera is turned off',
    deniedBody: 'To take pictures, allow OnlySwap to use the Camera in Settings.',
  },
  photos: {
    title: 'Add photos from your library',
    body: 'OnlySwap only sees the photos you pick. You can choose just the ones you want to share.',
    cta: 'Continue',
    alternative: 'Use the camera instead',
    deniedTitle: 'Photos are turned off',
    deniedBody:
      'To add pictures, allow OnlySwap to use Photos in Settings. You can pick just the ones you want to share.',
  },
  notifications: {
    title: "Don't miss an offer",
    body: 'Most things sell within a few hours. We only notify you about offers, messages and stuff you saved.',
    cta: 'Turn on notifications',
    alternative: 'Not now',
    deniedTitle: 'Notifications are off',
    deniedBody:
      'To hear about offers and messages, turn on notifications for OnlySwap in Settings.',
  },
} as const;

/** Report sheet (P2-CMP-11, board B9, E19). Reason keys match DATA_MODEL reports.reason. */
export const report = {
  titleListing: 'Report this listing',
  titleMessage: 'Report this message',
  titlePerson: 'Report {name}',
  them: 'They',
  seller: 'The seller',
  private: "Reports are private. {name} won't know it was you.",
  reasonLabel: 'Reason',
  reasons: {
    listing: {
      scam: 'Looks like a scam',
      not_allowed: "It's not allowed (vapes, alcohol, weapons and more)",
      stolen: 'Might be stolen',
      counterfeit: 'Fake or counterfeit',
      misleading: 'Wrong photos or misleading',
      harassment: 'Harassment',
      threat: 'Threats or feeling unsafe',
      hate: 'Hate or slurs',
      sexual: 'Sexual content',
      no_show: "Didn't show up",
      minor_safety: 'Involves someone under 18',
      other: 'Something else',
    },
    person: {
      scam: 'Scam or fake payment',
      not_allowed: "Selling something that's not allowed",
      stolen: 'Selling something stolen',
      counterfeit: 'Selling fakes',
      misleading: 'Misleading about an item',
      harassment: 'Harassment or unwanted messages',
      threat: 'Threats or feeling unsafe',
      hate: 'Hate or slurs',
      sexual: 'Sexual content',
      no_show: "Didn't show up",
      minor_safety: 'Involves someone under 18',
      other: 'Something else',
    },
  },
  detailsLabel: 'Add details (optional)',
  detailsPlaceholderListing: 'Example: my bike was stolen from outside the library last week',
  detailsPlaceholderPerson: 'Example: kept messaging me after I said no',
  alsoBlock: 'Also block {name}',
  blockHint: "They can't message you, make offers or see your listings.",
  send: 'Send report',
  sentTitle: 'Report sent',
  sentBody: "Thanks for telling us. We'll look into it, usually within a day.",
  sentBodyBlocked:
    "Thanks for telling us. You blocked {name}, and we'll look into it, usually within a day.",
  duplicateTitle: 'Already reported',
  duplicateBody: "You've already reported this. We're on it.",
  done: 'Done',
} as const;

/** Dev-build-only spike screen (P1-SPIKE-03/04). Not shown in store builds. */
export const dev = {
  open: 'Open developer spikes',
  openHint: 'Opens the dev-only test screen',
  title: 'Developer spikes',
  mmkvLabel: 'MMKV counter (survives a reload)',
  mmkvButton: 'Add one',
  mmkvHint: 'Adds one to the saved counter',
  unistylesLabel: 'Unistyles theme',
  unistylesButton: 'Switch theme',
  unistylesHint: 'Switches between light and dark',
  ageLabel: 'OS age signal',
  mediaLabel: 'Photo pipeline (EXIF check)',
  mediaRun: 'Process GPS photo',
  mediaUpload: 'Process and upload as avatar',
  mediaBefore: 'Before:',
  mediaAfter: 'After:',
  mediaPass: 'PASS: no location data in the output',
  mediaFail: 'FAIL: the output still has location data',
  mediaSignIn: 'Sign in first to test the upload.',
  mediaUploaded: 'Uploaded',
  mediaError: 'Error:',
  ageButton: 'Ask for age range',
  ageHint: 'Asks the system for your age range',
  ageNotAsked: 'Not asked yet',
  ageUnknown: 'Unknown',
  keyboardLabel: 'Keyboard avoiding field',
  keyboardHint: 'Type to check the field stays above the keyboard',
  keyboardPlaceholder: 'Type here',
  themeLabel: 'Appearance',
  themeHint: 'Changes light or dark mode right away',
  themeModes: { system: 'System', light: 'Light', dark: 'Dark' },
  typeLabel: 'Type scale',
  typeSample: 'Swap a desk lamp for a bike light',
  typePrice: '$1,234.50',
  typeOverlay: 'Photo overlay text stops growing at 1.4x',
  motionFull: 'Motion: full',
  motionReduced: 'Motion: reduced (fades only)',
  motionButton: 'Show success',
  motionHint: 'Plays or clears the success check',
  motionDone: 'Done',
} as const;

/** Dev-build-only component kit (P2-KIT-01). Sample copy, not shipped UI. */
export const kit = {
  open: 'Open component kit',
  title: 'Component kit',
  buttons: 'Buttons',
  primary: 'Post item',
  dark: 'Make an offer',
  secondary: 'Save for later',
  text: 'Not now',
  destructive: 'Delete listing',
  loading: 'Sending',
  disabled: 'Unavailable',
  iconBack: 'Back',
  iconShare: 'Share',
  iconMore: 'More options',
  inputs: 'Inputs',
  email: 'School email',
  emailPlaceholder: 'you@school.edu',
  price: 'Price',
  search: 'Search listings',
  searchPlaceholder: 'Search',
  name: 'First name',
  nameError: 'Use letters only.',
  disabledField: 'Campus',
  description: 'Description',
  code: 'Verification code',
  codeError: 'Show code error',
  controls: 'Controls',
  categories: 'Categories',
  catBooks: 'Books',
  catTech: 'Tech',
  catDorm: 'Dorm',
  catFree: 'Free',
  condition: 'Condition',
  condNew: 'New',
  condGood: 'Good',
  condFair: 'Fair',
  removable: 'Under $20',
  remove: 'remove filter',
  alerts: 'Price drop alerts',
  alertsHint: 'Get a push when a saved item gets cheaper',
  pickup: 'Pickup only',
  meetup: 'Meet on campus',
  agree: 'I agree to the community rules',
  quantity: 'Quantity',
  decrease: 'Decrease',
  increase: 'Increase',
  overlays: 'Sheets and toasts',
  openSheet: 'Open sheet',
  openActions: 'Open actions',
  sheetTitle: 'Make an offer',
  sheetBody: 'Drag down, tap outside or use back to close. Type below to check the keyboard.',
  offerAmount: 'Your offer',
  actionsTitle: 'Listing',
  actionShare: 'Share listing',
  actionReport: 'Report listing',
  showToast: 'Show toast',
  toastMessage: 'Offer sent',
  showUndo: 'Show undo toast',
  undoMessage: 'Listing hidden',
  showError: 'Show error toast',
  errorMessage: "Couldn't send. Try again.",
  banners: 'Banners',
  bannerInfo: 'Finals week: meetups close at 9 PM.',
  bannerWarning: 'Your account needs a quick re-verify.',
  surfaces: 'Cards, rows and tags',
  cardTitle: 'Desk lamp',
  cardMeta: 'Posted 2 hours ago',
  tagNew: 'New',
  tagAccent: 'Founding seller',
  tagGreen: 'Verified',
  tagAmber: 'On hold',
  tagRed: 'Sold',
  settings: 'Account',
  rowEmail: 'Email',
  rowEmailValue: 'you@school.edu',
  rowNotifications: 'Notifications',
  rowDelete: 'Delete account',
  settingsFooter: 'Deleting removes your listings and chats.',
  avatarA: 'Maya Chen',
  avatarB: 'Jordan',
  avatarC: 'Sam Rivera',
} as const;

/** Dev-build-only kit additions for S6 (P2-KIT-01). Sample copy, not shipped UI. */
export const kit2 = {
  accent: 'Accent preview',
  photos: 'Photos',
  photoAlt: 'Mini fridge, 3.1 cubic feet',
  photoLoading: 'Loading',
  photoLoaded: 'Loaded',
  photoError: 'Failed',
  states: 'Empty, error and loading',
  emptyTitle: 'Nothing listed yet',
  emptyBody: 'Listing takes about a minute. Things that sell fastest here:',
  emptyAction: 'List your first thing',
  sugBooks: 'Textbooks',
  sugFridge: 'Mini fridges',
  sugChair: 'Desk chairs',
  sugLamp: 'Lamps',
  sugFree: 'Free stuff',
  navigation: 'Navigation',
  newListing: 'New listing',
  stepCount: '1 of 3',
  offer: 'Offer',
  more: 'More options',
  tabIos: 'Tab bar, iOS',
  tabAndroid: 'Tab bar, Android (board N1)',
  nextStep: 'Next step',
  uploading: 'Uploading photo 2',
  addProgress: 'Add progress',
  primers: 'Permission primers',
  primerKind: 'Permission',
  camera: 'Camera',
  photosKind: 'Photos',
  notifications: 'Notifications',
  showPrimer: 'Show primer',
  showDenied: 'Show denied',
  dialogs: 'Dialogs and reports',
  openConfirm: 'Delete a listing',
  reportListing: 'Report a listing',
  reportPerson: 'Report a person',
  confirmTitle: 'Delete this listing?',
  confirmBody: 'It stops showing to buyers. Chats about it stay so nobody loses a deal.',
  confirmAction: 'Delete listing',
  deleted: 'Listing deleted',
  personName: 'Ben O.',
  openStates: 'Open states gallery',
} as const;

/** Dev-build-only states gallery (P2-KIT-02): fixture copy for every board X frame. */
export const statesFx = {
  title: 'States gallery',
  intro: 'Every X frame from the design board, rendered with S6 components and fixtures.',
  release: 'Release {release}',
  realScreen: 'Real screen: {screen}',
  notInR10: 'Not in R1.0',
  pendingTitle: 'Built in a later session',
  pendingBody:
    'This state belongs to {screen}. It gets its real fixture when that screen is built ({task}).',
  removedBody: 'Removed from R1.0 ({reason}). Kept here so every board frame stays reachable.',
  laterBody: 'Planned for release {release}. Kept here so every board frame stays reachable.',
  emailLabel: 'School email',
  emailPlaceholder: 'you@school.edu',
  sendCode: 'Send code',
  loginTitle: 'Welcome back',
  loginBody: "Enter your school email and we'll send a code. No password to remember.",
  codeTitle: 'Enter the code',
  codeWrong: "That code isn't right. 2 tries left.",
  cachedRow: 'Dell 24 inch monitor',
  cachedValue: '$50',
  noResultsTitle: 'No standing desks under $30',
  noResultsBody: '3 show up if you remove the price filter.',
  noResultsAction: 'Show 3 results over $30',
  noResultsSave: "Tell me when one's listed",
  inboxTitle: 'No offers yet',
  inboxBody:
    'Offers you make and offers on your stuff show up here. Chats open once an offer is accepted.',
  startSwiping: 'Start swiping',
  sessionTitle: "Quick check it's you",
  sessionBody: "It's been a while. We sent a code to your school email.",
  continue: 'Continue',
  logOut: 'Log out instead',
  reverifyTitle: 'Still a student here?',
  reverifyBody: 'Once a year we check that everyone is a current student. It takes 20 seconds.',
  remindLater: 'Remind me next week',
  pausedTitle: 'Your account is paused',
  pausedBody:
    'A listing broke the banned items rule. You can still read and finish chats you already had open.',
  appeal: 'Appeal this',
  readRules: 'Read the rules',
  appealTitle: 'What happened?',
  appealMistake: 'This was a mistake',
  appealUnaware: "I didn't know the rule",
  appealSomeoneElse: 'Someone else used my account',
  appealDetails: 'Tell us your side',
  sendAppeal: 'Send appeal',
  updateTitle: 'Time to update',
  updateBody: "This version can't send offers anymore. The update keeps everything you had.",
  updateAction: 'Update OnlySwap',
  maintenanceTitle: 'Back in about 15 minutes',
  maintenanceBody:
    "We're upgrading things behind the scenes. Nothing you've listed or saved is affected.",
  goneTitle: 'This one sold',
  goneBody: 'Your offers were closed automatically. Similar things are still up.',
  goneAction: 'See similar',
  reviewBanner: 'Your calculator listing is being reviewed. Most reviews take under 2 hours.',
  reviewRow: 'Calculator and notes',
  reviewTag: 'In review',
  draftTitle: 'Pick up where you left off?',
  draftBody: 'You started listing a monitor yesterday.',
  startOver: 'Start over',
  uploadRetry: 'Upload failed. Tap to retry.',
  blockedBanner: "You blocked Ben. He can't message you or see your listings.",
  unblock: 'Unblock',
  undoSkipped: 'Skipped Mini fridge',
  showUndo: 'Show the undo toast',
  otherCampusTitle: 'This listing is at another campus',
  otherCampusBody: 'Only students there can see it. Here is what is close on your campus.',
  otherCampusAction: 'Browse similar',
  signedOutTitle: 'Sign in to see it',
  signedOutBody: 'Listings are only visible to verified students. It takes 30 seconds.',
  largeTextBody:
    'Set the largest text size in Settings, then check this list: names wrap and buttons grow.',
  notificationsTitle: 'All quiet',
  notificationsBody: 'Offers, messages, price drops and meetup reminders will show up here.',
  notificationSettings: 'Notification settings',
  savedTitle: 'No saved items',
  savedBody:
    "Tap the bookmark on any card to save it. You'll hear about price drops and when it sells.",
  bannedRows: {
    alcohol: 'Alcohol, vapes, nicotine and weed',
    drugs: 'Medication and drugs',
    weapons: 'Weapons',
    fakes: 'Fakes and IDs',
  },
} as const;

/** Launch and Welcome (A01, A02). */
export const launch = {
  label: 'OnlySwap is starting',
} as const;

export const welcome = {
  wordmark: 'onlyswap',
  title: 'Buy and sell with students at your school.',
  body: 'Dorm stuff, textbooks, tech. Meet between classes and pay in person.',
  continue: 'Continue with school email',
  signIn: 'I already have an account',
  signInHint: 'Signs in with the code we email to your school address',
  /** Floating sample listings on the hero photo (decorative, hidden from screen readers). */
  samples: [
    { title: 'Mini fridge', price: '$40', place: 'North dorms' },
    { title: 'Chem textbooks', price: '$25', place: 'Main library' },
    { title: '27 inch monitor', price: '$90', place: 'East hall' },
  ],
} as const;

/** S-A03 School email, S-A04 Verify code (boards A3, A4, A5, A6, X1, X2). */
export const signIn = {
  titleSignUp: "What's your school email?",
  titleSignIn: 'Sign in with your school email',
  body: "We'll send a 6-digit code to check you're a student.",
  emailLabel: 'School email',
  emailPlaceholder: 'you@school.edu',
  checking: 'Checking your school',
  reviewAccount: '{school} · review account',
  sendCode: 'Send code',
  signInReviewer: 'Sign in',
  passwordLabel: 'Password',
  personal: "That's a personal email. Use the one your school gave you, ending in .edu.",
  invalid: 'Check the email. It should look like you@school.edu.',
  alumniTitle: 'Graduated, or work at the school?',
  alumniBody: "OnlySwap is only for current students, so alumni and staff emails can't join.",
  unknownTitle: "We're not at {domain} yet",
  unknownBody: "Join the waitlist and we'll email you when your school opens.",
  joinWaitlist: 'Join the waitlist',
  waitlistJoined: "You're on the list. We'll email you when your school opens.",
  wrongPassword: "That email and password don't match.",
  // Verify code
  verifyTitle: 'Enter the code',
  sentTo: 'Sent to {email}. It expires in 10 minutes.',
  codeLabel: '6-digit code',
  verifying: 'Checking the code',
  wrongCode: "That code isn't right. {count} tries left.",
  wrongCodeOne: "That code isn't right. 1 try left.",
  expired: 'This code expired. We just sent you a new one.',
  locked: 'Too many tries. Wait {time}, or get a new code.',
  resendIn: 'Nothing yet? Check spam, or resend in {time}.',
  resend: 'Resend code',
  resent: 'New code sent.',
  differentEmail: 'Use a different email',
  cantAccessEmail: "Can't get into your school email?",
} as const;

/** A05 Birthday and A8 Not eligible (boards A7, A8). */
export const age = {
  checking: 'Checking your age',
  title: "When's your birthday?",
  body: "We ask everyone. It's never shown on your profile.",
  fieldLabel: 'Birthday',
  fieldPlaceholder: 'Choose a date',
  privacy: 'Used only to confirm you can use OnlySwap. Details in the Privacy Policy.',
  continue: 'Continue',
  invalidDate: 'Check the date and try again.',
  step: '3 of 5',
  blockedTitle: "OnlySwap isn't available to you yet",
  blockedBody:
    "You need to be 18 or older to use OnlySwap. We haven't kept your email or any details.",
  blockedCardTitle: 'Selling something before then?',
  blockedCardBody: "Ask a friend who's 18 or older to post it for you and meet together.",
  close: 'Close',
} as const;

/** A06 Profile setup (board A10). */
export const profileSetup = {
  step: '4 of 5',
  title: 'Set up your profile',
  body: 'This is what buyers and sellers see.',
  addPhoto: 'Add a photo',
  changePhoto: 'Change photo',
  photoHint: 'Makes you easier to spot at pickup.',
  photoLabel: 'Profile photo',
  uploading: 'Uploading your photo',
  uploaded: 'Photo added',
  uploadFailed: "Your photo didn't upload. Try again, or continue without it.",
  removePhoto: 'Remove photo',
  firstName: 'First name',
  lastName: 'Last name',
  lastNameHint: 'Only the first letter is shown.',
  shownAs: 'Shown as {name}',
  year: 'Year',
  years: {
    freshman: 'Freshman',
    sophomore: 'Sophomore',
    junior: 'Junior',
    senior: 'Senior',
    grad: 'Grad',
  },
  nameEmpty: 'Add your first name.',
  nameTooLong: 'Keep it to 30 letters or fewer.',
  nameInvalid: 'Use letters only. Spaces, hyphens and apostrophes are fine.',
  continue: 'Continue',
  waitForPhoto: 'Wait for the photo to finish uploading',
} as const;

/** A07 Community rules (board A11) and the D10 Updated rules variant. */
export const rules = {
  step: '5 of 5',
  title: 'Four rules',
  body: 'Everyone here agrees to these. Break them and your account comes down.',
  updatedTitle: 'We updated the rules',
  updatedBody: 'Read what changed, then agree to keep using OnlySwap.',
  whatChanged: 'What changed',
  noChangeList: 'The community rules were reworded. Read them again below.',
  items: [
    {
      icon: 'pin',
      title: 'Meet in public',
      body: 'Use a Meetup spot or a busy place on campus. Not a dorm room, not an empty parking lot.',
    },
    {
      icon: 'tag',
      title: 'Pay in person',
      body: 'Cash, Venmo, whatever you both agree on. OnlySwap never touches the money.',
    },
    {
      icon: 'ban',
      title: 'Nothing on the banned list',
      body: 'No alcohol, vapes, meds, weapons, fakes, tickets, meal swipes or coursework.',
    },
    {
      icon: 'chat',
      title: 'Keep chats about the deal',
      body: 'Anything creepy gets reported and looked at by a real person.',
    },
  ],
  agreeLabel: "I'm 18 or older and agree to the Community Rules, Terms and Privacy Policy",
  communityRules: 'Community Rules',
  terms: 'Terms',
  privacy: 'Privacy Policy',
  openLink: 'Opens {page} in your browser',
  agree: 'Agree and continue',
} as const;

/** A08 Notifications primer (board A12). Sample notifications are decorative. */
export const notifyPrimer = {
  samples: [
    {
      time: 'now',
      title: 'Devin accepted your offer',
      body: 'Mini fridge for $35. Say hi and plan the pickup.',
    },
    {
      time: '4m ago',
      title: 'Price drop on something you saved',
      body: 'Desk chair is now $30. It was $45.',
    },
    { time: '12m ago', title: 'New message from Priya', body: 'Can we meet at the library at 3?' },
  ],
  turnOn: 'Turn on notifications',
  notNow: 'Not now',
  openSettings: 'Open Settings',
} as const;

/** X7 Session expired (board X7). */
export const sessionExpired = {
  title: "Quick check it's you",
  body: "It's been a while. We sent a code to {email}.",
  wrongCode: "That code isn't right. Check the latest email and try again.",
  continue: 'Continue',
  logOut: 'Log out instead',
} as const;

/** X9 Re-verify (board X9). */
export const reverify = {
  title: 'Still at {school}?',
  titleNoSchool: 'Still a student?',
  body: 'Once a year we check that everyone is a current student. It takes 20 seconds, same code as when you signed up.',
  emailLabel: 'School email',
  dueLabel: 'Due by',
  sendCode: 'Send code',
  logOut: 'Log out',
  graduated:
    'Graduated or no longer a student? OnlySwap is only for current students, so you can close your account from Settings.',
} as const;

/** F20 "I can't get into my school email" (D11). */
export const emailAccess = {
  title: "Can't get into your school email?",
  body: "Tell us how to reach you. We'll check it's you and move your account to your new school email.",
  contactLabel: 'Email we can reach you at',
  contactPlaceholder: 'you@example.com',
  contactInvalid: 'Check the email. We need it to reply.',
  schoolLabel: 'School email on your account',
  schoolPlaceholder: 'you@school.edu',
  messageLabel: 'What happened',
  messagePlaceholder: 'For example, your school moved you to a new address.',
  messageEmpty: 'Add a short note so we can help.',
  note: 'A real person reads this, usually within two days. We never ask for your password.',
  send: 'Send',
  sentTitle: 'We got your message',
  sentBody: "We'll reply to {email}. Keep an eye on your spam folder too.",
  done: 'Done',
} as const;

/** Sell steps 1 and 2 (P5-SELL-02, P5-SELL-03; board D1 to D4, X15 uploads and drafts). */
export const sell = {
  title: 'New listing',
  stepCount: '{step} of {total}',
  next: 'Next',
  close: 'Close',
  // Step 1: photos
  photosTitle: 'Add photos',
  photosBody: 'Up to 8. The first one is the cover.',
  savedJustNow: 'Draft saved',
  savedAgo: 'Draft saved · {time}',
  camera: 'Camera',
  library: 'Library',
  cover: 'Cover',
  removePhoto: 'Remove photo {n}',
  photoLabel: 'Photo {n} of {total}',
  photoCoverLabel: 'Photo {n} of {total}, cover',
  uploading: 'Uploading',
  retry: 'Retry',
  retryLabel: 'Photo {n} did not upload. Retry',
  moveEarlier: 'Move earlier',
  moveLater: 'Move later',
  makeCover: 'Make cover',
  reorderHint: 'Hold and drag to reorder.',
  tip: 'Shoot near a window on a plain surface. Show any scratches or dents, it saves a lot of back and forth.',
  full: 'That is 8 photos, the most a listing can have.',
  needPhoto: 'Add at least one photo to keep going.',
  waitUploads: 'Photos are still uploading.',
  fixUploads: "Retry or remove the photos that didn't upload.",
  reserveFailed: "We couldn't start your listing. Check your connection and try again.",
  // Restore sheet (board X15)
  restoreTitle: 'Pick up where you left off?',
  restoreBodyNamed: 'You started listing {title} {when}.',
  restoreBody: 'You started a listing {when}.',
  startOver: 'Start over',
  continue: 'Continue',
  // Step 2: details
  sellIt: 'Sell it',
  giveAway: 'Give it away',
  modeLabel: 'Sell or give away',
  titleLabel: 'Title',
  titlePlaceholder: 'What is it?',
  categoryLabel: 'Category',
  categoryPlaceholder: 'Pick a category',
  categoriesTitle: 'Pick a category',
  categoriesFailed: "Categories didn't load.",
  conditionLabel: 'Condition',
  conditions: { new: 'New', like_new: 'Like new', good: 'Good', fair: 'Fair' },
  priceLabel: 'Price',
  pricePlaceholder: '$0',
  offersLabel: 'Open to offers',
  offersBody: 'People can offer less than your price. You decide.',
  pickupLabel: 'Pick up by',
  pickup: { tomorrow: 'Tomorrow', sunday: 'Sunday', week: 'This week' },
  freeTitle: 'Goes on the Free shelf',
  freeBody: 'Free things usually go within a day. You pick who gets it from the people who ask.',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'Brand, size, what is included, any flaws.',
  fixCount: '{count} things to fix before you can post',
  fixOne: '1 thing to fix before you can post',
  errors: {
    titleShort: 'Add a title with at least 3 characters.',
    titleLong: 'Keep the title under 80 characters.',
    banned: '"{term}" isn\'t allowed on OnlySwap. Check the banned items in the rules.',
    category: 'Pick one so the right people see it',
    priceMissing: 'Add a price, or switch to Give it away.',
    priceLow: 'Prices start at $1. For free, switch to Give it away.',
    priceHigh:
      'Prices go up to $2,000. For anything more, meet somewhere staffed and bring a friend.',
    descriptionLong: 'Keep the description under 1000 characters.',
    checkFailed: "We couldn't check the text. Check your connection and try again.",
  },
  // Step 3: meetup (board D5)
  meetupTitle: 'Where can you meet?',
  meetupBody: 'Buyers see this before they make an offer. Pick up to 5.',
  police: 'Police-designated',
  directions: 'Directions',
  directionsLabel: 'Directions to {name}',
  decideInChat: 'Decide in chat',
  decideInChatBody: 'You and the buyer pick a spot',
  spotsMax: 'Pick up to 5 spots.',
  spotsFailed: "Meetup spots didn't load.",
  noSpots: 'No meetup spots here yet. You and the buyer can pick one in chat.',
  noteLabel: 'Somewhere else? (optional)',
  notePlaceholder: 'For example, the lobby of your building',
  availabilityLabel: 'Usually free',
  availability: {
    weekdays: 'Weekdays',
    weekends: 'Weekends',
    mornings: 'Mornings',
    afternoons: 'Afternoons',
    evenings: 'Evenings',
  },
  preview: 'Preview',
  free: 'Free',
  notBanned: "This isn't on the banned items list",
  confirmBanned: 'Confirm it is allowed to post.',
  post: 'Post listing',
  postFailed: "We couldn't post it. Your draft is saved, try again in a moment.",
  // Step 4: posted (board D6)
  postedTitle: 'Your listing is up',
  postedBody:
    "It's in your campus feed now. We'll tell you when someone saves it or makes an offer.",
  reviewTitle: 'Your listing is in review',
  reviewBody: "Most reviews take under 2 hours. We'll tell you when it's up.",
  postedCheck: 'Listing posted',
  share: 'Share listing',
  shareMessage: '{title} · {price} on OnlySwap',
  cardPreparing: 'Making the share preview',
  cardFailed: "The preview image didn't upload. Sharing still works with the link.",
  listAnother: 'List another',
  cardCampus: '{campus} only',
  cardCondition: '{condition} condition',
  ago: {
    now: 'just now',
    second: '1 second ago',
    seconds: '{n} seconds ago',
    minute: '1 minute ago',
    minutes: '{n} minutes ago',
    today: 'earlier today',
    yesterday: 'yesterday',
    days: '{n} days ago',
  },
} as const;

export const feed = {
  stampOffer: 'Offer',
  stampSkip: 'Skip',
  stampSave: 'Saved',
  skip: 'Skip',
  save: 'Save',
  saved: 'Saved',
  offer: 'Make an offer',
  open: 'See details',
  /** Spoken card summary: title, price, condition, seller. */
  cardLabel: '{title}, {price}',
  cardHint: 'Swipe right to make an offer, left to skip. Actions menu has more.',
  savedBy: '{n} people saved this',
  savedByOne: '1 person saved this',
  photoCount: 'Photo {n} of {total}',
  listTitle: 'Listings',
  metaSeparator: ' · ',
  free: 'Free',
  // Discover (B01)
  title: 'Discover',
  search: 'Search',
  undoSkipped: 'Skipped',
  undoSaved: 'Saved',
  undoOffer: 'Opened the offer',
  saveFailed: "Couldn't save that. Try again.",
  coachTitle: 'Swipe to shop',
  coachBody: 'Swipe right or tap $ to make an offer. Left skips. Tap a card to see more.',
  coachOk: 'Got it',
  endTitle: "You've seen everything for now",
  endBody: 'New stuff usually shows up in the evening.',
  endSell: 'List something',
  endRefresh: 'Check again',
  dayOneTitle: "It's early days here",
  dayOneBody: 'Only a few things are listed so far. Post yours and be one of the first.',
  loading: 'Loading listings',
  // Listing (B02)
  back: 'Back',
  share: 'Share',
  more: 'More options',
  shareMessage: '{title}, {price} on OnlySwap',
  descriptionTitle: 'About this item',
  meetupTitle: 'Meetup',
  meetupDecide: 'You and the seller pick a spot in chat.',
  availabilityTitle: 'Usually free',
  sellerTitle: 'Seller',
  sellerNew: 'New seller',
  statViews: '{n} views',
  statSaves: '{n} saves',
  statOffers: '{n} offers',
  edit: 'Edit',
  seeOffers: 'See offers',
  onHold: 'On hold',
  onHoldBody: 'Someone is meeting up for this. It may come back.',
  tellMe: 'Tell me if it comes back',
  watching: "We'll tell you",
  sold: 'Sold',
  inReview: 'In review',
  notOpenToOffers: 'Price is firm',
  askForIt: 'Ask for it',
  goneTitle: 'This listing is gone',
  goneBody: 'It was sold, taken down or expired.',
  blockedTitle: "You can't see this listing",
  blockedBody: "You or the seller blocked the other, so it's hidden.",
  otherCampusTitle: 'This listing is at another campus',
  otherCampusBody: 'OnlySwap only shows listings from your own campus.',
  backToDiscover: 'Back to Discover',
  // Options (B03)
  optionsTitle: 'Options',
  notInterested: 'Not interested',
  notInterestedDone: "We won't show it again",
  reportListing: 'Report listing',
  hideFailed: "Couldn't hide it. Try again.",
  // Photos (B04)
  photoOf: 'Photo {n} of {total}, {title}',
  closePhotos: 'Close photos',
} as const;

export const search = {
  title: 'Search',
  placeholder: 'Search your campus',
  inputLabel: 'Search',
  cancel: 'Cancel',
  recent: 'Recent',
  clearRecent: 'Clear',
  trending: 'Popular right now',
  suggestionsLabel: 'Suggestions',
  savedLabel: 'Saved search',
  categoryLabel: 'Category',
  countLabel: '{n} listed',
  resultsTitle: 'Results for "{q}"',
  allTitle: 'All listings',
  filters: 'Filters',
  filtersActive: 'Filters, {n} on',
  saveSearch: 'Save search',
  searchSaved: "Search saved. We'll tell you about new matches.",
  saveFailed: "Couldn't save the search. Try again.",
  noResultsTitle: 'Nothing matches yet',
  noResultsBody: 'Save this search and we will tell you when something shows up.',
  noResultsClear: 'Clear filters',
  // Filters sheet (B08)
  category: 'Category',
  price: 'Price',
  minPrice: 'Min',
  maxPrice: 'Max',
  condition: 'Condition',
  freeOnly: 'Free stuff only',
  hideSwiped: 'Hide things I skipped',
  sort: 'Sort',
  sorts: {
    relevance: 'Best match',
    new: 'Newest',
    price_asc: 'Lowest price',
    price_desc: 'Highest price',
  },
  apply: 'Show results',
  reset: 'Reset',
  // Tiles
  tileSold: 'Sold',
  tileHold: 'On hold',
  tileLabel: '{title}, {price}',
} as const;

export const saved = {
  title: 'Saved',
  open: 'Saved items',
  items: 'Items',
  searches: 'Searches',
  priceDropped: 'Price dropped',
  unsave: 'Remove {title} from saved',
  unsaveAction: 'Remove from saved',
  emptyItemsTitle: 'Nothing saved yet',
  emptyItemsBody: 'Tap the bookmark on anything you like and it shows up here.',
  emptySearchesTitle: 'No saved searches',
  emptySearchesBody: 'Save a search and we will tell you when something new matches.',
  goDiscover: 'Start swiping',
  goSearch: 'Search',
  allListings: 'All listings',
  newCount: '{n} new',
  alerts: 'Alerts',
  alertsFor: 'Alerts for {q}',
  deleteSearch: 'Delete {q}',
  deleteAction: 'Delete',
  filtersOnly: 'Filtered search',
} as const;

export const profileView = {
  memberSince: 'Joined {date}',
  swaps: '{n} swaps',
  swapsOne: '1 swap',
  thumbs: '{pct}% thumbs up',
  noRatings: 'No ratings yet',
  replies: 'Usually replies in {time}',
  minutes: '{n} min',
  hours: '{n} h',
  newSeller: 'New seller',
  newSellerBody:
    "They haven't finished a swap here yet. Meet at a Meetup spot and check the item first.",
  founding: 'Founding seller',
  listings: 'Listings',
  noListings: 'Nothing listed right now.',
  reviews: 'Reviews',
  noReviews: 'No reviews yet.',
  deletedUser: 'Deleted user',
  thumbsUp: 'Thumbs up',
  thumbsDown: 'Thumbs down',
  report: 'Report {name}',
  block: 'Block {name}',
  blockTitle: 'Block {name}?',
  blockBody: "They can't message you, make offers or see your listings. You won't see theirs.",
  blockConfirm: 'Block',
  blocked: 'You blocked {name}',
  blockedBody: "You won't see each other's listings or messages.",
  unblock: 'Unblock',
  goneTitle: "This profile isn't available",
  goneBody: 'The account may be gone or not on your campus.',
  more: 'More options',
  years: {
    freshman: 'Freshman',
    sophomore: 'Sophomore',
    junior: 'Junior',
    senior: 'Senior',
    grad: 'Grad student',
    other: 'Student',
  },
} as const;

export const offers = {
  // Offer sheet (B05)
  sheetTitle: 'Make an offer',
  askTitle: 'Ask for it',
  asking: 'Asking {price}',
  amountLabel: 'Your offer',
  quickAsk: 'Asking',
  quickLess: '{pct}% less',
  lowWarning: "That's under half the asking price. Low offers are usually declined.",
  firmNote: 'The price is firm, so offers are at the asking price.',
  notesLabel: 'Add a note (optional)',
  notePlaceholder: 'Example: I can pick it up tonight',
  quickNotes: {
    today: 'Can pick up today',
    campus: 'Can meet on campus',
    available: 'Is it still available?',
    cash: 'Paying cash',
  },
  send: 'Send offer',
  sendAsk: 'Ask for it',
  askBody: "It's free. Ask the giver and they'll pick who gets it.",
  sentTitle: 'Offer sent',
  askedTitle: 'Request sent',
  sentBody: "We'll tell you when {name} answers. Offers last 48 hours.",
  goInbox: 'Go to Inbox',
  keepSwiping: 'Keep swiping',
  close: 'Close',
  unavailableTitle: "This item isn't taking offers",
  pausedTitle: 'Offers are paused',
  // Inbox (E01)
  inboxTitle: 'Inbox',
  tabOffers: 'Offers',
  tabChats: 'Chats',
  waitingOnYou: 'Waiting on you',
  youMade: 'Offers you made',
  toYou: 'Offers to you',
  recent: 'Recent',
  emptyTitle: 'No offers or chats yet',
  emptyBody: 'Offers you make and get show up here. Chats start when a seller accepts.',
  emptyChatsTitle: 'No chats yet',
  emptyChatsBody: 'A chat opens when an offer is accepted.',
  startSwiping: 'Start swiping',
  unread: 'Unread',
  you: 'You: ',
  deletedUser: 'Deleted user',
  // Status lines (E3-E8)
  status: {
    pending_seller: '{name} offered {amount}',
    pending_buyer: 'You offered {amount}. Waiting for {name}.',
    countered_mine: '{name} countered at {amount}',
    countered_theirs: 'You countered at {amount}. Waiting for {name}.',
    accepted: 'Accepted at {amount}',
    declined: 'Declined',
    expired: 'Expired',
    withdrawn: 'Withdrawn',
    auto_declined: 'This sold to someone else',
    hold_other: 'On hold with someone else',
  },
  expiresIn: 'Expires {when}',
  round: 'Round {n} of 4',
  accept: 'Accept {amount}',
  counter: 'Counter',
  decline: 'Decline',
  withdraw: 'Withdraw offer',
  openChat: 'Open chat',
  offerAgain: 'Offer again',
  counterTitle: 'Counter offer',
  counterSend: 'Send counter',
  declineTitle: 'Decline this offer?',
  declineReasons: { low: 'Too low', sold: 'Selling to someone else', keep: 'Keeping it' },
  declineConfirm: 'Decline',
  withdrawTitle: 'Withdraw your offer?',
  withdrawBody: 'The seller will no longer see it.',
  withdrawConfirm: 'Withdraw',
  lastRound: 'This is the last round. They can accept or decline.',
  // Offers on a listing (F05)
  listingOffersTitle: 'Offers',
  noOffers: 'No offers yet',
  noOffersBody: 'Offers show up here in the order they came in.',
} as const;

export const chat = {
  composerLabel: 'Message',
  composerPlaceholder: 'Message',
  send: 'Send',
  sending: 'Sending',
  failed: "Didn't send. Tap to retry.",
  retry: 'Retry',
  safetyTitle: 'Stay safe',
  safetyBody:
    'Meet at a Meetup spot in daylight, check the item, and pay in person. Never pay before you meet.',
  scamHint: {
    payment: 'Never pay before you meet. OnlySwap deals are paid in person.',
    link: 'Be careful with links. Keep the deal in this chat.',
    phone: 'Keep the deal in this chat until you meet.',
  },
  agreed: 'Agreed {amount}',
  planMeetup: 'Plan meetup',
  markSold: 'Mark sold',
  didItSell: 'Did it sell?',
  details: 'Chat details',
  closed: 'This chat is closed.',
  blocked: "You can't message each other.",
  youBlocked: 'You blocked {name}.',
  deletedUser: 'Deleted user',
  loadOlder: 'Load earlier messages',
  empty: 'Say hi and plan the pickup.',
  // Details (E04)
  detailsTitle: 'Chat details',
  mute: 'Mute notifications',
  viewListing: 'View listing',
  viewProfile: 'View profile',
  report: 'Report {name}',
  block: 'Block {name}',
  hide: 'Hide chat',
  hideDone: 'Chat hidden. It comes back if they message you.',
} as const;

export const meetup = {
  // Plan the pickup (E05)
  planTitle: 'Plan the pickup',
  spotsTitle: 'Meetup spots',
  police: 'Police-designated',
  directions: 'Directions to {name}',
  directionsShort: 'Directions',
  somewhereElse: 'Somewhere else',
  customLabel: 'Place',
  customPlaceholder: 'For example, the lobby of Morrill Tower',
  dayTitle: 'Day',
  timeTitle: 'Time',
  today: 'Today',
  tomorrow: 'Tomorrow',
  suggest: 'Suggest this time',
  accept: 'Accept',
  suggestAnother: 'Suggest another',
  theySuggested: '{name} suggested {when} at {place}',
  youSuggested: 'You suggested {when} at {place}. Waiting for {name}.',
  noSpots: 'No Meetup spots here yet. Type a public place.',
  // Card in chat (P8-MEET-04)
  cardProposed: 'Suggested: {when}',
  cardConfirmed: 'Meetup set: {when}',
  cardCancelled: 'Meetup cancelled',
  cardDone: 'Meetup done',
  cardNoShow: 'Marked as a no-show',
  open: 'Open meetup',
  // Meetup day (E06)
  dayScreenTitle: 'Meetup',
  startsIn: 'Starts in {time}',
  startedAgo: 'Started {time} ago',
  minutes: '{n} min',
  hoursMinutes: '{h} h {m} min',
  imHere: "I'm here",
  youreHere: "You're here",
  theyreHere: '{name} is here',
  notHereYet: "{name} hasn't checked in",
  runningLate: "I'm running late",
  lateBy: '{n} min',
  youAreLate: 'You told them you are {n} min late',
  theyAreLate: '{name} is running {n} min late',
  cancel: 'Cancel meetup',
  cancelTitle: 'Cancel this meetup?',
  cancelBody: "We'll tell {name}. You can plan a new time in the chat.",
  cancelConfirm: 'Cancel meetup',
  keep: 'Keep it',
  reschedule: 'Pick another time',
  share: 'Share with a friend',
  shareMessage: "I'm meeting someone from OnlySwap. See where and when: {url}",
  noShow: "They didn't show up",
  noShowTitle: 'Report a no-show?',
  noShowBody: 'Use this only if you were there and they never came. They can appeal.',
  noShowConfirm: 'Report no-show',
  noShowSent: "Thanks. We'll look into it.",
  emergency: 'Call 911',
  emergencyHint: 'If you ever feel unsafe, leave and call 911.',
  cancelled: 'This meetup was cancelled.',
  rescheduledFrom: 'Moved from {when}',
} as const;

export const deal = {
  // Did it sell? (E07)
  didItSellTitle: 'Did it sell?',
  didYouGetItTitle: 'Did you get it?',
  done: 'Yes, all done',
  notYet: 'Not yet',
  fellThrough: 'It fell through',
  fellThroughTitle: 'Close this deal?',
  fellThroughBody: 'The chat closes and the listing goes back up.',
  fellThroughConfirm: 'Close deal',
  // Mark sold (F07)
  markSoldTitle: 'Who bought it?',
  markSoldBody: 'Pick the buyer so you can rate each other. Other chats close.',
  someoneElse: 'Someone not on OnlySwap',
  markSold: 'Mark sold',
  // Rate (E08)
  rateTitle: 'Rate the swap',
  rateQuestion: 'How was swapping with {name}?',
  thumbsUp: 'Good',
  thumbsDown: 'Not great',
  tagsLabel: 'What stood out? (optional)',
  tags: {
    on_time: 'On time',
    as_described: 'As described',
    friendly: 'Friendly',
    easy: 'Easy to deal with',
    late: 'Late',
    not_as_described: 'Not as described',
    rude: 'Rude',
    no_show: "Didn't show",
  },
  commentLabel: 'Add a comment (optional)',
  commentPlaceholder: 'Example: quick and easy pickup',
  submit: 'Send rating',
  waitingTitle: 'Thanks for rating',
  waitingBody: 'Their rating shows up when they rate too, or after 7 days.',
  revealedTitle: 'Your ratings',
  theirRating: '{name} said',
  youSaid: 'You said',
  done_: 'Done',
} as const;

export const notificationsScreen = {
  title: 'Notifications',
  open: 'Notifications',
  openUnread: 'Notifications, {n} unread',
  markAll: 'Mark all read',
  today: 'Today',
  yesterday: 'Yesterday',
  earlier: 'Earlier',
  emptyTitle: 'No notifications yet',
  emptyBody: 'Offers, messages and meetup updates show up here.',
  unread: 'Unread',
  // Settings (F11)
  settingsTitle: 'Notifications',
  osOff: 'Notifications are off for OnlySwap in your phone settings.',
  openSettings: 'Open settings',
  offers: 'Offers',
  offersBody: 'New offers, counters and answers',
  messages: 'Messages',
  messagesBody: 'New chat messages',
  meetups: 'Meetups',
  meetupsBody: 'Suggestions, reminders and changes',
  savedSearch: 'Saved searches',
  savedSearchBody: 'New matches and items back from hold',
  priceDrop: 'Price drops',
  priceDropBody: 'When something you saved gets cheaper',
  tips: 'Selling tips',
  tipsBody:
    'Occasional nudges, like when a listing gets no offers. These are promotional and off unless you turn them on.',
  previews: 'Show message text',
  previewsBody: 'Off by default. When on, a push can show what someone wrote.',
  quiet: 'Quiet hours',
  quietBody: 'No pushes from {start} to {end}, except meetup reminders and time-sensitive updates.',
  quietStart: 'Start',
  quietEnd: 'End',
  saveFailed: "Couldn't save that. Try again.",
} as const;

export const safety = {
  // X10 account status
  statusTitle: {
    paused: 'Your account is paused',
    suspended: 'Your account is suspended',
    banned: 'Your account is closed',
  },
  statusBody: {
    paused:
      'You can still read and finish your open chats. Offers and new listings are off until {until}.',
    pausedNoDate:
      'You can still read and finish your open chats. Offers and new listings are off for now.',
    suspended:
      'A moderator suspended your account after a report. You can appeal once and a person reviews it.',
    banned: 'This account broke the rules in a way that ends access to OnlySwap.',
  },
  reasons: {
    noshow: 'Missed meetups',
    strike: 'A rule was broken',
    report: 'A report was upheld',
  },
  strikesTitle: 'Strikes',
  noshowsTitle: 'No-shows',
  openChats: 'Open my chats',
  appeal: 'Appeal',
  appealed: 'Appeal sent. A person will review it.',
  appealDecided: {
    upheld: 'Your appeal was reviewed. The decision stays.',
    overturned: 'Your appeal was accepted.',
  },
  signOut: 'Sign out',
  contact: 'Contact support',
  // X10a appeal sheet
  appealTitle: 'Appeal',
  appealReasons: {
    mistake: "I didn't do this",
    context: "There's more to the story",
    other: 'Something else',
  },
  appealBody: 'Tell us what happened',
  appealPlaceholder: 'Stick to the facts. A person reads every appeal.',
  appealSend: 'Send appeal',
  // E21 report update
  reportTitle: 'Your report',
  reportReceived: 'Received',
  reportReviewed: 'Reviewed',
  reportReceivedBody: 'We got your report. A person looks at it, usually within a day.',
  reportReviewedBody:
    "We reviewed your report and took the action we thought was right. We don't share details to protect everyone's privacy.",
  // F13 blocked
  blockedTitle: 'Blocked accounts',
  blockedEmptyTitle: "You haven't blocked anyone",
  blockedEmptyBody: 'People you block show up here. You can unblock them anytime.',
  unblock: 'Unblock',
  unblockName: 'Unblock {name}',
  // F19 safety center
  centerTitle: 'Safety',
  spotsTitle: 'Meetup spots',
  spotsBody: 'Public places on campus. Police-designated spots are marked.',
  police: 'Police-designated',
  directions: 'Directions to {name}',
  tipsTitle: 'Before you meet',
  tips: [
    'Meet at a Meetup spot in daylight.',
    'Tell a friend where you are going. You can share your meetup from the app.',
    'Check the item before you pay.',
    'Pay in person. Never pay before you meet, and never send a deposit.',
    'If something feels off, leave. You can cancel anytime.',
  ],
  emergency: 'Call 911',
  emergencyBody: 'If you are in danger, call 911 right away.',
  bannedTitle: 'Banned items',
  bannedIntro: "These can't be listed on OnlySwap:",
  banned: [
    'Alcohol, vapes, nicotine and weed',
    'Medication, supplements and drugs',
    'Weapons, including pepper spray and knives',
    'Fake IDs, fakes and counterfeits',
    'Tickets, meal swipes and parking passes',
    'Coursework, exams and essays',
    'Pets and animals',
    'Gift cards and money transfers',
    'Recalled or unsafe items',
    'Stolen items',
  ],
  // F20 help
  helpTitle: 'Help',
  faqTitle: 'Common questions',
  faq: [
    {
      q: 'How do I pay?',
      a: 'In person, when you meet. Cash or any app you both agree on. OnlySwap never handles money.',
    },
    {
      q: 'Who can see my listings?',
      a: 'Only verified students at your school. People you block and people who block you cannot.',
    },
    {
      q: 'What if someone does not show up?',
      a: 'Open the meetup and report a no-show after 20 minutes. You must have checked in.',
    },
    {
      q: 'How do I delete my account?',
      a: 'Settings, then Delete account. Your listings and profile are removed right away.',
    },
    {
      q: 'Why do I need to confirm my school email again?',
      a: 'Once a year we check you are still a student so everyone here is.',
    },
    {
      q: 'Someone is making me uncomfortable. What do I do?',
      a: 'Block them from their profile or the chat and report them. A real person reviews every report.',
    },
  ],
  contactTitle: 'Contact us',
  contactTopic: 'Topic',
  topics: { general: 'Question', safety: 'Safety', bug: 'Something is broken', other: 'Other' },
  contactEmail: 'Your email',
  contactBody: 'Message',
  contactSend: 'Send',
  contactSent: "Thanks. We'll reply by email.",
  // F16 delete account
  deleteTitle: 'Delete account',
  deleteBody:
    'This removes your profile, listings and saved items for good. People you chatted with will see a deleted user. This cannot be undone.',
  deleteType: 'Type DELETE to confirm',
  deleteButton: 'Delete my account',
  deleteFailed: "We couldn't delete your account. Try again or contact support.",
} as const;

export const me = {
  // F01 Profile tab
  title: 'Profile',
  verifiedAt: 'Verified at {campus}',
  statsActive: '{n} listed',
  statsSold: '{n} sold',
  statsSwaps: '{n} swaps',
  sellNudgeTitle: 'Got something to sell?',
  sellNudgeBody: 'It takes a minute. Most things get an offer the same week.',
  sellNudge: 'List something',
  viewProfile: 'View my public profile',
  myListings: 'My listings',
  saved: 'Saved',
  notifications: 'Notifications',
  settings: 'Settings',
  safety: 'Safety',
  help: 'Help',
  edit: 'Edit profile',
  // F02 Edit profile
  editTitle: 'Edit profile',
  firstName: 'First name',
  lastInitial: 'Last initial',
  year: 'Year',
  bio: 'About you (optional)',
  bioPlaceholder: 'Example: junior, lives on north campus',
  changePhoto: 'Change photo',
  uploading: 'Uploading photo',
  save: 'Save',
  saved_: 'Saved',
  // F03 My listings
  listingsTitle: 'My listings',
  tabs: { active: 'Active', sold: 'Sold', other: 'Other' },
  listingsEmptyTitle: 'Nothing listed yet',
  listingsEmptyBody: 'Your listings show up here.',
  statusLabels: {
    active: 'Active',
    hold: 'On hold',
    sold: 'Sold',
    expired: 'Expired',
    held_review: 'In review',
    removed: 'Removed',
  },
  relist: 'Relist',
  stats: 'Stats',
  // F04 Listing stats
  statsTitle: 'Listing stats',
  views: 'Views',
  saves: 'Saves',
  offers: 'Offers',
  openOffers: 'Open offers',
  bestOffer: 'Best open offer',
  listed: 'Listed {date}',
  expires: 'Expires {date}',
  priceHistory: 'Price changes',
  noPriceChanges: 'No price changes yet',
  // F06 Edit listing
  editListingTitle: 'Edit listing',
  titleLabel: 'Title',
  descriptionLabel: 'Description',
  priceLabel: 'Price',
  openToOffers: 'Open to offers',
  saveChanges: 'Save changes',
  deleteListing: 'Delete listing',
  deleteTitle: 'Delete this listing?',
  deleteBody: 'It disappears for everyone. Open offers are declined and chats close.',
  deleteConfirm: 'Delete listing',
  // F08 Relist
  relistTitle: 'Relist',
  relistBody: 'Your listing goes back to the top of the deck for 60 days.',
  relistPrice: 'New price (optional)',
  relistButton: 'Relist',
  relisted: 'Relisted',
} as const;

export const settings = {
  title: 'Settings',
  account: 'Account',
  notifications: 'Notifications',
  privacy: 'Privacy',
  appearance: 'Appearance',
  school: 'Change school email',
  blocked: 'Blocked accounts',
  data: 'Download my data',
  about: 'About',
  signOut: 'Sign out',
  signOutAll: 'Sign out of all devices',
  signOutAllTitle: 'Sign out everywhere?',
  signOutAllBody: 'Every phone signed in to this account signs out, including this one.',
  signOutAllConfirm: 'Sign out everywhere',
  deleteAccount: 'Delete account',
  // F12 privacy
  privacyTitle: 'Privacy',
  analytics: 'Share usage stats',
  analyticsBody:
    'Anonymous counts that help us fix what is confusing. Never your messages or listings.',
  crash: 'Send crash reports',
  crashBody: 'When the app crashes, send a report without your name or email.',
  // F14 appearance
  appearanceTitle: 'Appearance',
  modes: { system: 'Match phone', light: 'Light', dark: 'Dark' },
  // F15 change school
  schoolTitle: 'Change school email',
  schoolBody:
    "Moving to a new school email? We'll send a code to the new address. Your account and listings stay.",
  schoolEmail: 'New school email',
  schoolSend: 'Send code',
  schoolSent: 'Check {email} for a link or code to confirm the change.',
  // F18 about
  aboutTitle: 'About',
  version: 'Version {version}',
  terms: 'Terms',
  privacyPolicy: 'Privacy Policy',
  rules: 'Community Rules',
  licenses: 'Open source licenses',
  licensesBody:
    'OnlySwap is built with open source software including React Native, Expo, Supabase and others, each under its own license.',
  contact: 'Contact us',
  dataBody: 'Ask for a copy of your data and we will email it within 30 days.',
} as const;

export const system = {
  // X11 update required
  updateTitle: 'Time to update',
  updateBody: 'This version of OnlySwap is too old to keep working. Update to keep swapping.',
  updateButton: 'Update OnlySwap',
  // X12 maintenance
  maintenanceTitle: "We'll be right back",
  maintenanceBody: 'OnlySwap is getting some work done.',
  maintenanceUntil: 'Back around {time}.',
  tryAgain: 'Try again',
  // X31 link errors
  linkErrorTitle: "That link didn't work",
  linkErrorBody: 'It may be old or copied wrong. The listing might also be gone.',
  notFoundTitle: 'Nothing here',
  notFoundBody: "We couldn't find that page in the app.",
  goHome: 'Go to Discover',
  // X14 under review
  underReview:
    'Your listing is being checked by a moderator. It shows to others once it is approved.',
} as const;

export const en = {
  permissions,
  tabs,
  shell,
  errors,
  sheet,
  toast,
  banner,
  photo,
  states,
  nav,
  primer,
  report,
  dev,
  kit,
  kit2,
  statesFx,
  launch,
  welcome,
  signIn,
  age,
  profileSetup,
  rules,
  notifyPrimer,
  sessionExpired,
  reverify,
  emailAccess,
  sell,
  feed,
  search,
  saved,
  profileView,
  offers,
  chat,
  meetup,
  deal,
  notificationsScreen,
  safety,
  me,
  settings,
  system,
} as const;

export default en;
