/**
 * Spanish (Latin American) copy for the mobile app (P17-FEAT-03, DEC 76).
 * Same keys as `en.ts`, which stays the source of truth: `Strings` makes
 * TypeScript fail on a missing or extra key. Same voice rules as en.ts:
 * plain student tone, tú, no em dashes, no emoji, verbs on buttons.
 * Glossary: Meetup spot = Punto de encuentro; Police-designated = Designado
 * por la policía; listing = publicación; offer = oferta; meetup = encuentro.
 */

import type { Strings } from './en';

const permissions: Strings['permissions'] = {
  camera:
    'OnlySwap usa la cámara para que tomes fotos de lo que vendes y una foto tuya para tu perfil.',
  photos: 'OnlySwap abre tus fotos para que elijas imágenes de lo que vendes y una foto de perfil.',
};

const tabs: Strings['tabs'] = {
  discover: 'Explorar',
  sell: 'Vender',
  inbox: 'Bandeja',
  profile: 'Perfil',
  quad: 'Quad',
};

const shell: Strings['shell'] = {
  discoverTitle: 'Explorar',
  sellTitle: 'Vender',
  inboxTitle: 'Bandeja',
  profileTitle: 'Perfil',
  comingSoon: 'Estamos construyendo esta pantalla.',
};

const errors: Strings['errors'] = {
  NOT_AUTHENTICATED: 'Inicia sesión para seguir.',
  NOT_ACTIVE: 'Tu cuenta no puede hacer eso ahora. Revisa tu perfil para ver detalles.',
  AGE_REQUIRED: 'Confirma que tienes 18 años o más para seguir.',
  RULES_REQUIRED: 'Lee y acepta las reglas de la comunidad para seguir.',
  FORBIDDEN: 'No tienes acceso a eso.',
  NOT_FOUND: 'No lo encontramos. Puede que lo hayan quitado.',
  INVALID: 'Hay algo que corregir en el formulario. Revisa los campos marcados.',
  BANNED_TERM: 'Ese texto tiene palabras que no se permiten en OnlySwap.',
  RATE_LIMITED: 'Lo estás haciendo mucho. Intenta de nuevo en un rato.',
  RATE_LIMITED_UNTIL: 'Lo estás haciendo mucho. Intenta de nuevo después de las {time}.',
  OFFERS_PAUSED: 'Las ofertas están en pausa en tu cuenta por un encuentro al que no llegaste.',
  LISTING_UNAVAILABLE: 'Esta publicación no está recibiendo ofertas ahora.',
  OFFER_NOT_PENDING: 'Esta oferta cambió. Desliza hacia abajo para actualizar.',
  ALREADY_REPORTED: 'Ya reportaste esto. Lo estamos revisando.',
  ALREADY_APPEALED: 'Ya enviaste una apelación. Te responderemos pronto.',
  MEETUP_WINDOW: 'Eso no se puede hacer en este momento del encuentro.',
  CHAT_CLOSED: 'Este chat está cerrado.',
  CHAT_BLOCKED: 'No puedes enviar mensajes en este chat.',
  NOT_ADMIN: 'Solo para admins.',
  SCHOOL_UNKNOWN: 'Todavía no aceptamos ese correo universitario.',
  DOMAIN_BLOCKED: 'Ese dominio de correo no se puede usar. Usa tu correo universitario.',
  AGE_BLOCKED: 'OnlySwap es para personas de 18 años o más.',
  BANNED: 'Esta cuenta fue eliminada de OnlySwap.',
  FEATURE_OFF: 'Eso todavía no está disponible.',
  ERR_OFFLINE: 'No tienes conexión. Revisa tu conexión e intenta de nuevo.',
  SESSION_EXPIRED: 'Tu sesión terminó. Inicia sesión otra vez.',
  UNKNOWN: 'Algo salió mal. Intenta de nuevo.',
};

const sheet: Strings['sheet'] = {
  close: 'Cerrar',
  cancel: 'Cancelar',
};

const toast: Strings['toast'] = {
  undo: 'Deshacer',
};

const banner: Strings['banner'] = {
  offline: 'No tienes conexión. Algunas cosas no se actualizan hasta que vuelvas a conectarte.',
};

const photo: Strings['photo'] = {
  count: '{index} / {count}',
  failed: 'La foto no cargó',
  openHint: 'Abre la foto en pantalla completa',
};

const states: Strings['states'] = {
  loading: 'Cargando',
  errorTitle: 'No se pudo cargar',
  offlineTitle: 'No tienes conexión',
  offlineBody: 'Revisa tu conexión e intenta de nuevo.',
  retry: 'Reintentar',
};

const nav: Strings['nav'] = {
  back: 'Atrás',
  close: 'Cerrar',
  tabWithBadge: '{label}, {count} nuevos',
  step: 'Paso {step} de {total}',
};

const primer: Strings['primer'] = {
  openSettings: 'Abrir Ajustes',
  camera: {
    title: 'Toma fotos de tus cosas',
    body: 'OnlySwap usa la cámara solo cuando agregas fotos a una publicación, a tu perfil o a un chat. No se graba nada en segundo plano.',
    cta: 'Continuar',
    alternative: 'Elegir de la galería',
    deniedTitle: 'La cámara está desactivada',
    deniedBody: 'Para tomar fotos, permite que OnlySwap use la Cámara en Ajustes.',
  },
  photos: {
    title: 'Agrega fotos de tu galería',
    body: 'OnlySwap solo ve las fotos que eliges. Puedes elegir solo las que quieras compartir.',
    cta: 'Continuar',
    alternative: 'Usar la cámara',
    deniedTitle: 'Las fotos están desactivadas',
    deniedBody:
      'Para agregar fotos, permite que OnlySwap use Fotos en Ajustes. Puedes elegir solo las que quieras compartir.',
  },
  notifications: {
    title: 'No te pierdas una oferta',
    body: 'La mayoría de las cosas se venden en pocas horas. Solo te avisamos de ofertas, mensajes y cosas que guardaste.',
    cta: 'Activar notificaciones',
    alternative: 'Ahora no',
    deniedTitle: 'Las notificaciones están desactivadas',
    deniedBody:
      'Para enterarte de ofertas y mensajes, activa las notificaciones de OnlySwap en Ajustes.',
  },
};

const report: Strings['report'] = {
  titleListing: 'Reportar esta publicación',
  titleMessage: 'Reportar este mensaje',
  titlePerson: 'Reportar a {name}',
  them: 'Esa persona',
  seller: 'Quien vende',
  private: 'Los reportes son privados. {name} no sabrá que fuiste tú.',
  reasonLabel: 'Motivo',
  reasons: {
    listing: {
      scam: 'Parece una estafa',
      not_allowed: 'No está permitido (vapes, alcohol, armas y más)',
      stolen: 'Puede ser robado',
      counterfeit: 'Falso o pirata',
      misleading: 'Fotos incorrectas o engañoso',
      harassment: 'Acoso',
      threat: 'Amenazas o me siento en peligro',
      hate: 'Odio o insultos',
      sexual: 'Contenido sexual',
      no_show: 'No llegó',
      minor_safety: 'Involucra a alguien menor de 18',
      calls_out_student: 'Expone a un estudiante',
      spam: 'Spam',
      self_harm: 'Alguien podría hacerse daño',
      other: 'Otra cosa',
    },
    person: {
      scam: 'Estafa o pago falso',
      not_allowed: 'Vende algo que no está permitido',
      stolen: 'Vende algo robado',
      counterfeit: 'Vende cosas falsas',
      misleading: 'Engaña sobre un artículo',
      harassment: 'Acoso o mensajes no deseados',
      threat: 'Amenazas o me siento en peligro',
      hate: 'Odio o insultos',
      sexual: 'Contenido sexual',
      no_show: 'No llegó',
      minor_safety: 'Involucra a alguien menor de 18',
      calls_out_student: 'Expone a un estudiante',
      spam: 'Spam o estafa',
      self_harm: 'Alguien podría hacerse daño',
      other: 'Otra cosa',
    },
    quad: {
      scam: 'Estafa',
      not_allowed: 'Algo que no está permitido',
      stolen: 'Cosas robadas',
      counterfeit: 'Cosas falsas',
      misleading: 'Engañoso',
      harassment: 'Acoso o bullying',
      threat: 'Amenaza o violencia',
      hate: 'Discurso de odio',
      sexual: 'Contenido sexual',
      no_show: 'No llegó',
      minor_safety: 'Involucra a alguien menor de 18',
      calls_out_student: 'Expone a un estudiante',
      spam: 'Spam o estafa',
      self_harm: 'Alguien podría hacerse daño',
      other: 'Otra cosa',
    },
  },
  titleQuadPost: 'Reportar esta publicación',
  titleQuadReply: 'Reportar esta respuesta',
  privateQuad: 'Los reportes también son anónimos.',
  crisisTitle: 'Si alguien está en peligro ahora mismo',
  crisisBody:
    'Llama o envía un mensaje al 988, la Línea de Prevención del Suicidio y Crisis, a cualquier hora. Es gratis y hay atención en español. Tu reporte igual llega a una persona aquí.',
  detailsPlaceholderQuad: 'Ejemplo: menciona a alguien de mi residencia',
  detailsLabel: 'Agrega detalles (opcional)',
  detailsPlaceholderListing: 'Ejemplo: me robaron la bici afuera de la biblioteca la semana pasada',
  detailsPlaceholderPerson: 'Ejemplo: me siguió escribiendo después de que le dije que no',
  alsoBlock: 'También bloquear a {name}',
  blockHint: 'No podrá escribirte, hacerte ofertas ni ver tus publicaciones.',
  send: 'Enviar reporte',
  sentTitle: 'Reporte enviado',
  sentBody: 'Gracias por avisarnos. Lo revisaremos, normalmente en menos de un día.',
  sentBodyBlocked:
    'Gracias por avisarnos. Bloqueaste a {name} y lo revisaremos, normalmente en menos de un día.',
  duplicateTitle: 'Ya lo reportaste',
  duplicateBody: 'Ya reportaste esto. Lo estamos revisando.',
  done: 'Listo',
};

const dev: Strings['dev'] = {
  open: 'Abrir pruebas de desarrollo',
  openHint: 'Abre la pantalla de pruebas solo para desarrollo',
  title: 'Pruebas de desarrollo',
  mmkvLabel: 'Contador MMKV (sobrevive a una recarga)',
  mmkvButton: 'Sumar uno',
  mmkvHint: 'Suma uno al contador guardado',
  unistylesLabel: 'Tema de Unistyles',
  unistylesButton: 'Cambiar tema',
  unistylesHint: 'Cambia entre claro y oscuro',
  ageLabel: 'Señal de edad del sistema',
  mediaLabel: 'Proceso de fotos (revisión EXIF)',
  mediaRun: 'Procesar foto con GPS',
  mediaUpload: 'Procesar y subir como avatar',
  mediaBefore: 'Antes:',
  mediaAfter: 'Después:',
  mediaPass: 'PASA: la salida no tiene datos de ubicación',
  mediaFail: 'FALLA: la salida todavía tiene datos de ubicación',
  mediaSignIn: 'Inicia sesión primero para probar la subida.',
  mediaUploaded: 'Subida',
  mediaError: 'Error:',
  ageButton: 'Pedir rango de edad',
  ageHint: 'Pide al sistema tu rango de edad',
  ageNotAsked: 'Todavía no se pidió',
  ageUnknown: 'Desconocido',
  keyboardLabel: 'Campo que evita el teclado',
  keyboardHint: 'Escribe para revisar que el campo quede arriba del teclado',
  keyboardPlaceholder: 'Escribe aquí',
  themeLabel: 'Apariencia',
  themeHint: 'Cambia al modo claro u oscuro al instante',
  themeModes: { system: 'Sistema', light: 'Claro', dark: 'Oscuro' },
  typeLabel: 'Escala de texto',
  typeSample: 'Cambia una lámpara por una luz de bici',
  typePrice: '$1,234.50',
  typeOverlay: 'El texto sobre fotos deja de crecer en 1.4x',
  motionFull: 'Movimiento: completo',
  motionReduced: 'Movimiento: reducido (solo fundidos)',
  motionButton: 'Mostrar éxito',
  motionHint: 'Muestra o quita la marca de éxito',
  motionDone: 'Listo',
};

const kit: Strings['kit'] = {
  open: 'Abrir kit de componentes',
  title: 'Kit de componentes',
  buttons: 'Botones',
  primary: 'Publicar',
  dark: 'Hacer una oferta',
  secondary: 'Guardar para después',
  text: 'Ahora no',
  destructive: 'Borrar publicación',
  loading: 'Enviando',
  disabled: 'No disponible',
  iconBack: 'Atrás',
  iconShare: 'Compartir',
  iconMore: 'Más opciones',
  inputs: 'Campos',
  email: 'Correo universitario',
  emailPlaceholder: 'tu@school.edu',
  price: 'Precio',
  search: 'Buscar publicaciones',
  searchPlaceholder: 'Buscar',
  name: 'Nombre',
  nameError: 'Usa solo letras.',
  disabledField: 'Campus',
  description: 'Descripción',
  code: 'Código de verificación',
  codeError: 'Mostrar error de código',
  controls: 'Controles',
  categories: 'Categorías',
  catBooks: 'Libros',
  catTech: 'Tecnología',
  catDorm: 'Residencia',
  catFree: 'Gratis',
  condition: 'Estado',
  condNew: 'Nuevo',
  condGood: 'Bueno',
  condFair: 'Regular',
  removable: 'Menos de $20',
  remove: 'quitar filtro',
  alerts: 'Alertas de baja de precio',
  alertsHint: 'Recibe un aviso cuando algo guardado baje de precio',
  pickup: 'Solo para recoger',
  meetup: 'Verse en el campus',
  agree: 'Acepto las reglas de la comunidad',
  quantity: 'Cantidad',
  decrease: 'Restar',
  increase: 'Sumar',
  overlays: 'Hojas y avisos',
  openSheet: 'Abrir hoja',
  openActions: 'Abrir acciones',
  sheetTitle: 'Hacer una oferta',
  sheetBody:
    'Desliza hacia abajo, toca afuera o usa atrás para cerrar. Escribe abajo para revisar el teclado.',
  offerAmount: 'Tu oferta',
  actionsTitle: 'Publicación',
  actionShare: 'Compartir publicación',
  actionReport: 'Reportar publicación',
  showToast: 'Mostrar aviso',
  toastMessage: 'Oferta enviada',
  showUndo: 'Mostrar aviso con deshacer',
  undoMessage: 'Publicación oculta',
  showError: 'Mostrar aviso de error',
  errorMessage: 'No se pudo enviar. Intenta de nuevo.',
  banners: 'Banners',
  bannerInfo: 'Semana de finales: los encuentros cierran a las 9 p. m.',
  bannerWarning: 'Tu cuenta necesita una verificación rápida.',
  surfaces: 'Tarjetas, filas y etiquetas',
  cardTitle: 'Lámpara de escritorio',
  cardMeta: 'Publicado hace 2 horas',
  tagNew: 'Nuevo',
  tagAccent: 'Vendedor fundador',
  tagGreen: 'Verificado',
  tagAmber: 'Apartado',
  tagRed: 'Vendido',
  settings: 'Cuenta',
  rowEmail: 'Correo',
  rowEmailValue: 'tu@school.edu',
  rowNotifications: 'Notificaciones',
  rowDelete: 'Borrar cuenta',
  settingsFooter: 'Al borrarla se quitan tus publicaciones y chats.',
  avatarA: 'Maya Chen',
  avatarB: 'Jordan',
  avatarC: 'Sam Rivera',
};

const kit2: Strings['kit2'] = {
  accent: 'Vista del acento',
  photos: 'Fotos',
  photoAlt: 'Minirrefri de 3.1 pies cúbicos',
  photoLoading: 'Cargando',
  photoLoaded: 'Cargada',
  photoError: 'Falló',
  states: 'Vacío, error y carga',
  emptyTitle: 'Todavía no hay nada publicado',
  emptyBody: 'Publicar toma como un minuto. Lo que más rápido se vende aquí:',
  emptyAction: 'Publica tu primera cosa',
  sugBooks: 'Libros de texto',
  sugFridge: 'Minirrefris',
  sugChair: 'Sillas de escritorio',
  sugLamp: 'Lámparas',
  sugFree: 'Cosas gratis',
  navigation: 'Navegación',
  newListing: 'Nueva publicación',
  stepCount: '1 de 3',
  offer: 'Oferta',
  more: 'Más opciones',
  tabIos: 'Barra de pestañas, iOS',
  tabAndroid: 'Barra de pestañas, Android (board N1)',
  nextStep: 'Siguiente paso',
  uploading: 'Subiendo foto 2',
  addProgress: 'Sumar progreso',
  primers: 'Avisos de permisos',
  primerKind: 'Permiso',
  camera: 'Cámara',
  photosKind: 'Fotos',
  notifications: 'Notificaciones',
  showPrimer: 'Mostrar aviso',
  showDenied: 'Mostrar denegado',
  dialogs: 'Diálogos y reportes',
  openConfirm: 'Borrar una publicación',
  reportListing: 'Reportar una publicación',
  reportPerson: 'Reportar a una persona',
  confirmTitle: '¿Borrar esta publicación?',
  confirmBody:
    'Deja de mostrarse a compradores. Los chats sobre ella se quedan para que nadie pierda un trato.',
  confirmAction: 'Borrar publicación',
  deleted: 'Publicación borrada',
  personName: 'Ben O.',
  openStates: 'Abrir galería de estados',
};

const statesFx: Strings['statesFx'] = {
  title: 'Galería de estados',
  intro: 'Cada pantalla X del board de diseño, hecha con componentes y datos de prueba de S6.',
  release: 'Versión {release}',
  realScreen: 'Pantalla real: {screen}',
  notInR10: 'No está en R1.0',
  pendingTitle: 'Se construye en una sesión posterior',
  pendingBody:
    'Este estado pertenece a {screen}. Recibe sus datos reales cuando se construya esa pantalla ({task}).',
  removedBody:
    'Se quitó de R1.0 ({reason}). Se deja aquí para que cada pantalla del board siga accesible.',
  laterBody:
    'Planeado para la versión {release}. Se deja aquí para que cada pantalla del board siga accesible.',
  emailLabel: 'Correo universitario',
  emailPlaceholder: 'tu@school.edu',
  sendCode: 'Enviar código',
  loginTitle: 'Qué bueno verte',
  loginBody: 'Escribe tu correo universitario y te enviamos un código. Sin contraseñas.',
  codeTitle: 'Escribe el código',
  codeWrong: 'Ese código no es correcto. Te quedan 2 intentos.',
  cachedRow: 'Monitor Dell de 24 pulgadas',
  cachedValue: '$50',
  noResultsTitle: 'No hay escritorios de pie por menos de $30',
  noResultsBody: 'Aparecen 3 si quitas el filtro de precio.',
  noResultsAction: 'Ver 3 resultados de más de $30',
  noResultsSave: 'Avísame cuando publiquen uno',
  inboxTitle: 'Todavía no hay ofertas',
  inboxBody:
    'Aquí aparecen las ofertas que haces y las que recibes. Los chats se abren cuando aceptan una oferta.',
  startSwiping: 'Empieza a deslizar',
  sessionTitle: 'Confirma que eres tú',
  sessionBody: 'Ha pasado un tiempo. Enviamos un código a tu correo universitario.',
  continue: 'Continuar',
  logOut: 'Mejor cerrar sesión',
  reverifyTitle: '¿Sigues estudiando aquí?',
  reverifyBody: 'Una vez al año revisamos que todos sigan estudiando. Toma 20 segundos.',
  remindLater: 'Recuérdame la próxima semana',
  pausedTitle: 'Tu cuenta está en pausa',
  pausedBody:
    'Una publicación rompió la regla de artículos prohibidos. Todavía puedes leer y terminar los chats que ya tenías abiertos.',
  appeal: 'Apelar',
  readRules: 'Leer las reglas',
  appealTitle: '¿Qué pasó?',
  appealMistake: 'Fue un error',
  appealUnaware: 'No conocía la regla',
  appealSomeoneElse: 'Alguien más usó mi cuenta',
  appealDetails: 'Cuéntanos tu versión',
  sendAppeal: 'Enviar apelación',
  updateTitle: 'Hora de actualizar',
  updateBody:
    'Esta versión ya no puede enviar ofertas. La actualización conserva todo lo que tenías.',
  updateAction: 'Actualizar OnlySwap',
  maintenanceTitle: 'Volvemos en unos 15 minutos',
  maintenanceBody:
    'Estamos mejorando cosas por dentro. Nada de lo que publicaste o guardaste se ve afectado.',
  goneTitle: 'Esto ya se vendió',
  goneBody: 'Tus ofertas se cerraron solas. Todavía hay cosas parecidas.',
  goneAction: 'Ver parecidos',
  reviewBanner:
    'Estamos revisando tu publicación de la calculadora. La mayoría de las revisiones toma menos de 2 horas.',
  reviewRow: 'Calculadora y apuntes',
  reviewTag: 'En revisión',
  draftTitle: '¿Sigues donde te quedaste?',
  draftBody: 'Ayer empezaste a publicar un monitor.',
  startOver: 'Empezar de nuevo',
  uploadRetry: 'No se pudo subir. Toca para reintentar.',
  blockedBanner: 'Bloqueaste a Ben. No puede escribirte ni ver tus publicaciones.',
  unblock: 'Desbloquear',
  undoSkipped: 'Saltaste Minirrefri',
  showUndo: 'Mostrar el aviso de deshacer',
  otherCampusTitle: 'Esta publicación es de otro campus',
  otherCampusBody: 'Solo lo ven estudiantes de allá. Esto es lo que hay cerca en tu campus.',
  otherCampusAction: 'Ver parecidos',
  signedOutTitle: 'Inicia sesión para verlo',
  signedOutBody: 'Las publicaciones solo las ven estudiantes verificados. Toma 30 segundos.',
  largeTextBody:
    'Pon el texto más grande en Ajustes y revisa esta lista: los nombres bajan de línea y los botones crecen.',
  notificationsTitle: 'Todo tranquilo',
  notificationsBody:
    'Aquí aparecen ofertas, mensajes, bajas de precio y recordatorios de encuentros.',
  notificationSettings: 'Ajustes de notificaciones',
  savedTitle: 'No hay guardados',
  savedBody:
    'Toca el marcador en cualquier tarjeta para guardarla. Te avisamos si baja de precio y cuando se venda.',
  bannedRows: {
    alcohol: 'Alcohol, vapes, nicotina y marihuana',
    drugs: 'Medicamentos y drogas',
    weapons: 'Armas',
    fakes: 'Falsificaciones e identificaciones',
  },
};

const launch: Strings['launch'] = {
  label: 'OnlySwap está iniciando',
};

const welcome: Strings['welcome'] = {
  wordmark: 'onlyswap',
  title: 'Compra y vende con estudiantes de tu universidad.',
  body: 'Cosas para tu cuarto, libros, tecnología. Vénganse a ver entre clases y paguen en persona.',
  continue: 'Seguir con correo universitario',
  signIn: 'Ya tengo una cuenta',
  signInHint: 'Inicia sesión con el código que enviamos a tu correo universitario',
  samples: [
    { title: 'Minirrefri', price: '$40', place: 'Residencias norte' },
    { title: 'Libros de química', price: '$25', place: 'Biblioteca central' },
    { title: 'Monitor de 27 pulgadas', price: '$90', place: 'Edificio este' },
  ],
};

const signIn: Strings['signIn'] = {
  titleSignUp: '¿Cuál es tu correo universitario?',
  titleSignIn: 'Inicia sesión con tu correo universitario',
  body: 'Te enviaremos un código de 6 dígitos para confirmar que eres estudiante.',
  emailLabel: 'Correo universitario',
  emailPlaceholder: 'tu@school.edu',
  checking: 'Revisando tu universidad',
  reviewAccount: '{school} · cuenta de revisión',
  sendCode: 'Enviar código',
  signInReviewer: 'Iniciar sesión',
  passwordLabel: 'Contraseña',
  personal: 'Ese es un correo personal. Usa el que te dio tu universidad, el que termina en .edu.',
  invalid: 'Revisa el correo. Debe verse como tu@school.edu.',
  alumniTitle: '¿Ya te graduaste o trabajas en la universidad?',
  alumniBody:
    'OnlySwap es solo para estudiantes actuales, así que los correos de exalumnos y personal no pueden entrar.',
  unknownTitle: 'Todavía no estamos en {domain}',
  unknownBody: 'Únete a la lista de espera y te escribimos cuando abra tu universidad.',
  joinWaitlist: 'Unirme a la lista',
  waitlistJoined: 'Ya estás en la lista. Te escribimos cuando abra tu universidad.',
  wrongPassword: 'Ese correo y esa contraseña no coinciden.',
  verifyTitle: 'Escribe el código',
  sentTo: 'Enviado a {email}. Vence en 10 minutos.',
  codeLabel: 'Código de 6 dígitos',
  verifying: 'Revisando el código',
  wrongCode: 'Ese código no es correcto. Te quedan {count} intentos.',
  wrongCodeOne: 'Ese código no es correcto. Te queda 1 intento.',
  expired: 'Este código venció. Te acabamos de enviar uno nuevo.',
  locked: 'Demasiados intentos. Espera {time} o pide un código nuevo.',
  resendIn: '¿Nada todavía? Revisa el spam o reenvía en {time}.',
  resend: 'Reenviar código',
  resent: 'Código nuevo enviado.',
  differentEmail: 'Usar otro correo',
  cantAccessEmail: '¿No puedes entrar a tu correo universitario?',
};

const age: Strings['age'] = {
  checking: 'Revisando tu edad',
  title: '¿Cuándo es tu cumpleaños?',
  body: 'Se lo preguntamos a todos. Nunca aparece en tu perfil.',
  newFromSignIn: 'Ese correo todavía no tenía cuenta, así que te estamos creando una.',
  fieldLabel: 'Cumpleaños',
  fieldPlaceholder: 'Elige una fecha',
  privacy:
    'Solo se usa para confirmar que puedes usar OnlySwap. Más detalles en el Aviso de privacidad.',
  continue: 'Continuar',
  invalidDate: 'Revisa la fecha e intenta de nuevo.',
  step: '3 de 5',
  blockedTitle: 'OnlySwap todavía no está disponible para ti',
  blockedBody:
    'Necesitas tener 18 años o más para usar OnlySwap. No guardamos tu correo ni ningún dato.',
  blockedCardTitle: '¿Quieres vender algo antes?',
  blockedCardBody:
    'Pídele a alguien de 18 años o más que lo publique por ti y vayan juntos al encuentro.',
  close: 'Cerrar',
};

const profileSetup: Strings['profileSetup'] = {
  step: '4 de 5',
  title: 'Arma tu perfil',
  body: 'Esto es lo que ven quienes compran y venden.',
  addPhoto: 'Agregar foto',
  changePhoto: 'Cambiar foto',
  photoHint: 'Así es más fácil reconocerte al entregar.',
  photoLabel: 'Foto de perfil',
  uploading: 'Subiendo tu foto',
  uploaded: 'Foto agregada',
  uploadFailed: 'Tu foto no se subió. Intenta de nuevo o sigue sin ella.',
  removePhoto: 'Quitar foto',
  firstName: 'Nombre',
  lastName: 'Apellido',
  lastNameHint: 'Solo se muestra la primera letra.',
  shownAs: 'Se muestra como {name}',
  year: 'Año',
  years: {
    freshman: 'Primer año',
    sophomore: 'Segundo año',
    junior: 'Tercer año',
    senior: 'Cuarto año',
    grad: 'Posgrado',
  },
  nameEmpty: 'Agrega tu nombre.',
  nameTooLong: 'Usa 30 letras o menos.',
  nameInvalid: 'Usa solo letras. Se aceptan espacios, guiones y apóstrofos.',
  continue: 'Continuar',
  waitForPhoto: 'Espera a que la foto termine de subir',
};

const rules: Strings['rules'] = {
  step: '5 de 5',
  title: 'Cuatro reglas',
  body: 'Aquí todos aceptan estas reglas. Si las rompes, tu cuenta se cierra.',
  updatedTitle: 'Actualizamos las reglas',
  updatedBody: 'Lee lo que cambió y acepta para seguir usando OnlySwap.',
  whatChanged: 'Qué cambió',
  noChangeList: 'Cambiamos la redacción de las reglas. Léelas otra vez abajo.',
  items: [
    {
      icon: 'pin',
      title: 'Véanse en público',
      body: 'Usa un Punto de encuentro o un lugar concurrido del campus. No un cuarto de residencia ni un estacionamiento vacío.',
    },
    {
      icon: 'tag',
      title: 'Paguen en persona',
      body: 'Efectivo, Venmo, lo que acuerden. OnlySwap nunca toca el dinero.',
    },
    {
      icon: 'ban',
      title: 'Nada de la lista prohibida',
      body: 'Nada de alcohol, vapes, medicamentos, armas, falsificaciones, boletos, comidas del plan ni tareas.',
    },
    {
      icon: 'chat',
      title: 'Que los chats sean sobre el trato',
      body: 'Cualquier cosa rara se reporta y la revisa una persona real.',
    },
  ],
  agreeLabel:
    'Tengo 18 años o más y acepto las Reglas de la comunidad, los Términos y el Aviso de privacidad',
  communityRules: 'Reglas de la comunidad',
  terms: 'Términos',
  privacy: 'Aviso de privacidad',
  openLink: 'Abre {page} en tu navegador',
  agree: 'Aceptar y continuar',
};

const notifyPrimer: Strings['notifyPrimer'] = {
  samples: [
    {
      time: 'ahora',
      title: 'Devin aceptó tu oferta',
      body: 'Minirrefri por $35. Salúdalo y planeen la entrega.',
    },
    {
      time: 'hace 4 min',
      title: 'Bajó de precio algo que guardaste',
      body: 'La silla de escritorio ahora cuesta $30. Antes costaba $45.',
    },
    {
      time: 'hace 12 min',
      title: 'Nuevo mensaje de Priya',
      body: '¿Nos vemos en la biblioteca a las 3?',
    },
  ],
  turnOn: 'Activar notificaciones',
  notNow: 'Ahora no',
  openSettings: 'Abrir Ajustes',
};

const sessionExpired: Strings['sessionExpired'] = {
  title: 'Confirma que eres tú',
  body: 'Ha pasado un tiempo. Enviamos un código a {email}.',
  wrongCode: 'Ese código no es correcto. Revisa el correo más reciente e intenta de nuevo.',
  continue: 'Continuar',
  logOut: 'Mejor cerrar sesión',
};

const reverify: Strings['reverify'] = {
  title: '¿Sigues en {school}?',
  titleNoSchool: '¿Sigues estudiando?',
  body: 'Una vez al año revisamos que todos sigan estudiando. Toma 20 segundos, con un código como cuando te registraste.',
  emailLabel: 'Correo universitario',
  dueLabel: 'Fecha límite',
  sendCode: 'Enviar código',
  logOut: 'Cerrar sesión',
  graduated:
    '¿Ya te graduaste o dejaste de estudiar? OnlySwap es solo para estudiantes actuales, así que puedes cerrar tu cuenta desde Ajustes.',
};

const emailAccess: Strings['emailAccess'] = {
  title: '¿No puedes entrar a tu correo universitario?',
  body: 'Dinos cómo contactarte. Confirmaremos que eres tú y pasaremos tu cuenta a tu nuevo correo universitario.',
  contactLabel: 'Correo donde te podemos escribir',
  contactPlaceholder: 'tu@ejemplo.com',
  contactInvalid: 'Revisa el correo. Lo necesitamos para responderte.',
  schoolLabel: 'Correo universitario de tu cuenta',
  schoolPlaceholder: 'tu@school.edu',
  messageLabel: 'Qué pasó',
  messagePlaceholder: 'Por ejemplo, tu universidad te cambió a una dirección nueva.',
  messageEmpty: 'Agrega una nota corta para poder ayudarte.',
  note: 'Lo lee una persona real, normalmente en menos de dos días. Nunca te pedimos tu contraseña.',
  send: 'Enviar',
  sentTitle: 'Recibimos tu mensaje',
  sentBody: 'Te responderemos a {email}. Revisa también tu carpeta de spam.',
  done: 'Listo',
};

const sell: Strings['sell'] = {
  title: 'Nueva publicación',
  stepCount: '{step} de {total}',
  next: 'Siguiente',
  close: 'Cerrar',
  photosTitle: 'Agrega fotos',
  photosBody: 'Hasta 8. La primera es la portada.',
  savedJustNow: 'Borrador guardado',
  savedAgo: 'Borrador guardado · {time}',
  camera: 'Cámara',
  library: 'Galería',
  cover: 'Portada',
  removePhoto: 'Quitar foto {n}',
  photoLabel: 'Foto {n} de {total}',
  photoCoverLabel: 'Foto {n} de {total}, portada',
  uploading: 'Subiendo',
  retry: 'Reintentar',
  retryLabel: 'La foto {n} no se subió. Reintentar',
  moveEarlier: 'Mover antes',
  moveLater: 'Mover después',
  makeCover: 'Hacer portada',
  reorderHint: 'Mantén presionado y arrastra para reordenar.',
  tip: 'Toma las fotos cerca de una ventana sobre una superficie lisa. Muestra rayones o golpes, te ahorra muchas preguntas.',
  full: 'Ya son 8 fotos, el máximo por publicación.',
  needPhoto: 'Agrega al menos una foto para seguir.',
  waitUploads: 'Las fotos todavía se están subiendo.',
  fixUploads: 'Reintenta o quita las fotos que no se subieron.',
  reserveFailed: 'No pudimos empezar tu publicación. Revisa tu conexión e intenta de nuevo.',
  restoreTitle: '¿Sigues donde te quedaste?',
  restoreBodyNamed: 'Empezaste a publicar {title} {when}.',
  restoreBody: 'Empezaste una publicación {when}.',
  startOver: 'Empezar de nuevo',
  continue: 'Continuar',
  sellIt: 'Venderlo',
  giveAway: 'Regalarlo',
  modeLabel: 'Vender o regalar',
  titleLabel: 'Título',
  titlePlaceholder: '¿Qué es?',
  categoryLabel: 'Categoría',
  categoryPlaceholder: 'Elige una categoría',
  categoriesTitle: 'Elige una categoría',
  categoriesFailed: 'Las categorías no cargaron.',
  conditionLabel: 'Estado',
  conditions: { new: 'Nuevo', like_new: 'Como nuevo', good: 'Bueno', fair: 'Regular' },
  priceLabel: 'Precio',
  pricePlaceholder: '$0',
  offersLabel: 'Acepto ofertas',
  offersBody: 'Pueden ofrecer menos de tu precio. Tú decides.',
  priceHint: 'Cosas parecidas aquí se vendieron entre {low} y {high} (lo normal es {typical})',
  priceHintUse: 'Usar {price}',
  priceHintUseHint: 'Pone {price} en el campo de precio',
  pickupLabel: 'Recoger antes de',
  pickup: { tomorrow: 'Mañana', sunday: 'Domingo', week: 'Esta semana' },
  freeTitle: 'Va a la sección Gratis',
  freeBody:
    'Lo gratis normalmente se va en un día. Tú eliges quién se lo lleva entre quienes lo pidan.',
  descriptionLabel: 'Descripción',
  descriptionPlaceholder: 'Marca, tamaño, qué incluye, algún defecto.',
  fixCount: '{count} cosas por corregir antes de publicar',
  fixOne: '1 cosa por corregir antes de publicar',
  errors: {
    titleShort: 'Agrega un título de al menos 3 caracteres.',
    titleLong: 'Usa menos de 80 caracteres en el título.',
    banned:
      '"{term}" no está permitido en OnlySwap. Revisa los artículos prohibidos en las reglas.',
    category: 'Elige una para que la vean las personas indicadas',
    priceMissing: 'Agrega un precio o cambia a Regalarlo.',
    priceLow: 'Los precios empiezan en $1. Para algo gratis, cambia a Regalarlo.',
    priceHigh:
      'Los precios llegan hasta $2,000. Para algo más caro, véanse en un lugar con personal y ve con alguien.',
    descriptionLong: 'Usa menos de 1000 caracteres en la descripción.',
    checkFailed: 'No pudimos revisar el texto. Revisa tu conexión e intenta de nuevo.',
  },
  meetupTitle: '¿Dónde pueden verse?',
  meetupBody: 'Quien compra lo ve antes de ofertar. Elige hasta 5.',
  police: 'Designado por la policía',
  directions: 'Cómo llegar',
  directionsLabel: 'Cómo llegar a {name}',
  decideInChat: 'Decidir en el chat',
  decideInChatBody: 'Tú y quien compra eligen un lugar',
  spotsMax: 'Elige hasta 5 lugares.',
  spotsFailed: 'Los Puntos de encuentro no cargaron.',
  noSpots: 'Todavía no hay Puntos de encuentro aquí. Pueden elegir uno en el chat.',
  noteLabel: '¿En otro lugar? (opcional)',
  notePlaceholder: 'Por ejemplo, el lobby de tu edificio',
  availabilityLabel: 'Normalmente libre',
  availability: {
    weekdays: 'Entre semana',
    weekends: 'Fines de semana',
    mornings: 'Mañanas',
    afternoons: 'Tardes',
    evenings: 'Noches',
  },
  preview: 'Vista previa',
  free: 'Gratis',
  notBanned: 'Esto no está en la lista de artículos prohibidos',
  confirmBanned: 'Marca la casilla de abajo para confirmar que está permitido.',
  post: 'Publicar',
  postFailed: 'No pudimos publicarlo. Tu borrador está guardado, intenta de nuevo en un momento.',
  postedTitle: 'Tu publicación ya está arriba',
  postedBody:
    'Ya aparece en el feed de tu campus. Te avisamos cuando alguien la guarde o haga una oferta.',
  reviewTitle: 'Tu publicación está en revisión',
  reviewBody: 'La mayoría de las revisiones toma menos de 2 horas. Te avisamos cuando esté arriba.',
  postedCheck: 'Publicación lista',
  share: 'Compartir publicación',
  shareMessage: '{title} · {price} en OnlySwap',
  cardPreparing: 'Creando la vista previa para compartir',
  cardFailed: 'La imagen de vista previa no se subió. Igual puedes compartir con el enlace.',
  listAnother: 'Publicar otra',
  cardCampus: 'Solo {campus}',
  cardCondition: 'Estado: {condition}',
  ago: {
    now: 'justo ahora',
    second: 'hace 1 segundo',
    seconds: 'hace {n} segundos',
    minute: 'hace 1 minuto',
    minutes: 'hace {n} minutos',
    today: 'hoy más temprano',
    yesterday: 'ayer',
    days: 'hace {n} días',
  },
};

const feed: Strings['feed'] = {
  stampOffer: 'Ofertar',
  stampSkip: 'Saltar',
  stampSave: 'Guardado',
  skip: 'Saltar',
  save: 'Guardar',
  saved: 'Guardado',
  offer: 'Hacer una oferta',
  open: 'Ver detalles',
  cardLabel: '{title}, {price}',
  cardHint:
    'Desliza a la derecha para ofertar, a la izquierda para saltar. El menú de acciones tiene más.',
  savedBy: '{n} personas guardaron esto',
  savedByOne: '1 persona guardó esto',
  photoCount: 'Foto {n} de {total}',
  listTitle: 'Publicaciones',
  metaSeparator: ' · ',
  free: 'Gratis',
  title: 'Explorar',
  search: 'Buscar',
  undoSkipped: 'Saltado',
  undoSaved: 'Guardado',
  undoOffer: 'Abriste la oferta',
  saveFailed: 'No se pudo guardar. Intenta de nuevo.',
  coachTitle: 'Desliza para comprar',
  coachBody:
    'Desliza a la derecha o toca $ para ofertar. A la izquierda saltas. Toca una tarjeta para ver más.',
  coachOk: 'Entendido',
  endTitle: 'Ya viste todo por ahora',
  endBody: 'Lo nuevo suele aparecer en la tarde.',
  endSell: 'Publicar algo',
  endRefresh: 'Revisar otra vez',
  dayOneTitle: 'Esto apenas empieza',
  dayOneBody: 'Hay pocas cosas publicadas. Publica lo tuyo y sé de los primeros.',
  loading: 'Cargando publicaciones',
  back: 'Atrás',
  share: 'Compartir',
  more: 'Más opciones',
  shareMessage: '{title}, {price} en OnlySwap',
  descriptionTitle: 'Sobre este artículo',
  meetupTitle: 'Encuentro',
  meetupDecide: 'Tú y quien vende eligen un lugar en el chat.',
  availabilityTitle: 'Normalmente libre',
  sellerTitle: 'Vendedor',
  sellerNew: 'Vendedor nuevo',
  statViews: '{n} vistas',
  statSaves: '{n} guardados',
  statOffers: '{n} ofertas',
  edit: 'Editar',
  seeOffers: 'Ver ofertas',
  onHold: 'Apartado',
  onHoldBody: 'Alguien va a verse para esto. Puede que vuelva.',
  tellMe: 'Avísame si vuelve',
  watching: 'Te avisaremos',
  sold: 'Vendido',
  inReview: 'En revisión',
  notOpenToOffers: 'Precio fijo',
  askForIt: 'Pedirlo',
  goneTitle: 'Esta publicación ya no está',
  goneBody: 'Se vendió, la quitaron o venció.',
  blockedTitle: 'No puedes ver esta publicación',
  blockedBody: 'Tú o quien vende bloqueó al otro, así que está oculta.',
  otherCampusTitle: 'Esta publicación es de otro campus',
  otherCampusBody: 'OnlySwap solo muestra publicaciones de tu propio campus.',
  backToDiscover: 'Volver a Explorar',
  optionsTitle: 'Opciones',
  notInterested: 'No me interesa',
  notInterestedDone: 'No lo volveremos a mostrar',
  reportListing: 'Reportar publicación',
  hideFailed: 'No se pudo ocultar. Intenta de nuevo.',
  photoOf: 'Foto {n} de {total}, {title}',
  closePhotos: 'Cerrar fotos',
};

const search: Strings['search'] = {
  title: 'Buscar',
  placeholder: 'Busca en tu campus',
  inputLabel: 'Buscar',
  cancel: 'Cancelar',
  recent: 'Recientes',
  clearRecent: 'Borrar',
  trending: 'Popular ahora',
  searchFor: 'Buscar "{q}"',
  suggestionsLabel: 'Sugerencias',
  savedLabel: 'Búsqueda guardada',
  categoryLabel: 'Categoría',
  countLabel: '{n} publicados',
  resultsTitle: 'Resultados de "{q}"',
  allTitle: 'Todas las publicaciones',
  filters: 'Filtros',
  filtersActive: 'Filtros, {n} activos',
  saveSearch: 'Guardar búsqueda',
  searchSaved: 'Búsqueda guardada. Te avisamos cuando haya resultados nuevos.',
  saveFailed: 'No se pudo guardar la búsqueda. Intenta de nuevo.',
  noResultsTitle: 'Todavía no hay resultados',
  noResultsBody: 'Guarda esta búsqueda y te avisamos cuando aparezca algo.',
  noResultsClear: 'Quitar filtros',
  category: 'Categoría',
  price: 'Precio',
  minPrice: 'Mín.',
  maxPrice: 'Máx.',
  condition: 'Estado',
  freeOnly: 'Solo cosas gratis',
  hideSwiped: 'Ocultar lo que salté',
  sort: 'Ordenar',
  sorts: {
    relevance: 'Más relevante',
    new: 'Más nuevo',
    price_asc: 'Menor precio',
    price_desc: 'Mayor precio',
  },
  apply: 'Ver resultados',
  reset: 'Restablecer',
  tileSold: 'Vendido',
  tileHold: 'Apartado',
  tileLabel: '{title}, {price}',
};

const saved: Strings['saved'] = {
  title: 'Guardados',
  open: 'Artículos guardados',
  items: 'Artículos',
  searches: 'Búsquedas',
  priceDropped: 'Bajó de precio',
  unsave: 'Quitar {title} de guardados',
  unsaveAction: 'Quitar de guardados',
  emptyItemsTitle: 'Todavía no guardas nada',
  emptyItemsBody: 'Toca el marcador en lo que te guste y aparecerá aquí.',
  emptySearchesTitle: 'No hay búsquedas guardadas',
  emptySearchesBody: 'Guarda una búsqueda y te avisamos cuando aparezca algo nuevo.',
  goDiscover: 'Empieza a deslizar',
  goSearch: 'Buscar',
  allListings: 'Todas las publicaciones',
  newCount: '{n} nuevos',
  alerts: 'Alertas',
  alertsFor: 'Alertas de {q}',
  deleteSearch: 'Borrar {q}',
  deleteAction: 'Borrar',
  filtersOnly: 'Búsqueda con filtros',
};

const profileView: Strings['profileView'] = {
  memberSince: 'Se unió en {date}',
  swaps: '{n} intercambios',
  swapsOne: '1 intercambio',
  thumbs: '{pct}% de pulgares arriba',
  noRatings: 'Sin calificaciones todavía',
  replies: 'Suele responder en {time}',
  minutes: '{n} min',
  hours: '{n} h',
  newSeller: 'Vendedor nuevo',
  newSellerBody:
    'Todavía no termina un intercambio aquí. Véanse en un Punto de encuentro y revisa el artículo primero.',
  founding: 'Vendedor fundador',
  listings: 'Publicaciones',
  noListings: 'No tiene nada publicado ahora.',
  reviews: 'Reseñas',
  noReviews: 'Todavía no hay reseñas.',
  deletedUser: 'Usuario eliminado',
  thumbsUp: 'Pulgar arriba',
  thumbsDown: 'Pulgar abajo',
  report: 'Reportar a {name}',
  block: 'Bloquear a {name}',
  blockTitle: '¿Bloquear a {name}?',
  blockBody:
    'No podrá escribirte, hacerte ofertas ni ver tus publicaciones. Tú no verás las suyas.',
  blockConfirm: 'Bloquear',
  blocked: 'Bloqueaste a {name}',
  blockedBody: 'No verán las publicaciones ni los mensajes del otro.',
  unblock: 'Desbloquear',
  goneTitle: 'Este perfil no está disponible',
  goneBody: 'La cuenta puede ya no existir o no ser de tu campus.',
  more: 'Más opciones',
  years: {
    freshman: 'Primer año',
    sophomore: 'Segundo año',
    junior: 'Tercer año',
    senior: 'Cuarto año',
    grad: 'Posgrado',
    other: 'Estudiante',
  },
};

const offers: Strings['offers'] = {
  sheetTitle: 'Hacer una oferta',
  askTitle: 'Pedirlo',
  asking: 'Pide {price}',
  amountLabel: 'Tu oferta',
  quickAsk: 'Lo que pide',
  quickLess: '{pct}% menos',
  lowWarning: 'Eso es menos de la mitad del precio. Las ofertas bajas suelen rechazarse.',
  firmNote: 'El precio es fijo, así que las ofertas son al precio pedido.',
  notesLabel: 'Agrega una nota (opcional)',
  notePlaceholder: 'Ejemplo: puedo recogerlo hoy en la noche',
  quickNotes: {
    today: 'Puedo recoger hoy',
    campus: 'Nos vemos en el campus',
    available: '¿Sigue disponible?',
    cash: 'Pago en efectivo',
  },
  send: 'Enviar oferta',
  sendAsk: 'Pedirlo',
  askBody: 'Es gratis. Pídelo y quien lo regala elige a quién se lo da.',
  sentTitle: 'Oferta enviada',
  askedTitle: 'Solicitud enviada',
  sentBody: 'Te avisamos cuando {name} responda. Las ofertas duran 48 horas.',
  goInbox: 'Ir a Bandeja',
  keepSwiping: 'Seguir deslizando',
  close: 'Cerrar',
  unavailableTitle: 'Este artículo no recibe ofertas',
  pausedTitle: 'Las ofertas están en pausa',
  inboxTitle: 'Bandeja',
  tabOffers: 'Ofertas',
  tabChats: 'Chats',
  waitingOnYou: 'Esperan tu respuesta',
  youMade: 'Ofertas que hiciste',
  toYou: 'Ofertas para ti',
  recent: 'Recientes',
  emptyTitle: 'Todavía no hay ofertas ni chats',
  emptyBody:
    'Aquí aparecen las ofertas que haces y recibes. Los chats empiezan cuando quien vende acepta.',
  emptyChatsTitle: 'Todavía no hay chats',
  emptyChatsBody: 'Se abre un chat cuando aceptan una oferta.',
  startSwiping: 'Empieza a deslizar',
  unread: 'Sin leer',
  you: 'Tú: ',
  deletedUser: 'Usuario eliminado',
  paneEmptyTitle: 'Elige un chat',
  paneEmptyBody: 'Elige una conversación a la izquierda para leerla y responder.',
  status: {
    pending_seller: '{name} ofreció {amount}',
    pending_buyer: 'Ofreciste {amount}. Esperando a {name}.',
    countered_mine: '{name} contraofertó {amount}',
    countered_theirs: 'Contraofertaste {amount}. Esperando a {name}.',
    accepted: 'Aceptada en {amount}',
    declined: 'Rechazada',
    expired: 'Vencida',
    withdrawn: 'Retirada',
    auto_declined: 'Se vendió a otra persona',
    hold_other: 'Apartado con otra persona',
  },
  expiresIn: 'Vence {when}',
  round: 'Ronda {n} de 4',
  accept: 'Aceptar {amount}',
  counter: 'Contraofertar',
  decline: 'Rechazar',
  withdraw: 'Retirar oferta',
  openChat: 'Abrir chat',
  offerAgain: 'Ofertar otra vez',
  counterTitle: 'Contraoferta',
  counterSend: 'Enviar contraoferta',
  declineTitle: '¿Rechazar esta oferta?',
  declineReasons: { low: 'Muy baja', sold: 'Se lo vendo a otra persona', keep: 'Me lo quedo' },
  declineConfirm: 'Rechazar',
  withdrawTitle: '¿Retirar tu oferta?',
  withdrawBody: 'Quien vende ya no la verá.',
  withdrawConfirm: 'Retirar',
  lastRound: 'Esta es la última ronda. Pueden aceptar o rechazar.',
  listingOffersTitle: 'Ofertas',
  noOffers: 'Todavía no hay ofertas',
  noOffersBody: 'Las ofertas aparecen aquí en el orden en que llegaron.',
};

const chat: Strings['chat'] = {
  composerLabel: 'Mensaje',
  composerPlaceholder: 'Mensaje',
  send: 'Enviar',
  sending: 'Enviando',
  failed: 'No se envió. Toca para reintentar.',
  retry: 'Reintentar',
  safetyTitle: 'Cuídate',
  safetyBody:
    'Véanse en un Punto de encuentro de día, revisa el artículo y paga en persona. Nunca pagues antes de verse.',
  scamHint: {
    payment: 'Nunca pagues antes de verse. En OnlySwap se paga en persona.',
    link: 'Cuidado con los enlaces. Mantén el trato en este chat.',
    phone: 'Mantén el trato en este chat hasta que se vean.',
  },
  agreed: 'Acordado en {amount}',
  planMeetup: 'Planear encuentro',
  markSold: 'Marcar vendido',
  didItSell: '¿Se vendió?',
  details: 'Detalles del chat',
  closed: 'Este chat está cerrado.',
  blocked: 'No pueden escribirse.',
  youBlocked: 'Bloqueaste a {name}.',
  deletedUser: 'Usuario eliminado',
  loadOlder: 'Cargar mensajes anteriores',
  empty: 'Saluda y planeen la entrega.',
  detailsTitle: 'Detalles del chat',
  mute: 'Silenciar notificaciones',
  viewListing: 'Ver publicación',
  viewProfile: 'Ver perfil',
  report: 'Reportar a {name}',
  block: 'Bloquear a {name}',
  hide: 'Ocultar chat',
  hideDone: 'Chat oculto. Vuelve si te escriben.',
  addPhoto: 'Agregar foto',
  photoSheetTitle: 'Enviar una foto',
  photoLibrary: 'Elegir de la galería',
  photoCamera: 'Tomar una foto',
  photoCaptionHint: 'Lo que escribiste se envía con la foto como texto.',
  photoLabel: 'Foto',
  photoFrom: 'Foto de {name}',
  yourPhoto: 'Tu foto',
  photoPreview: 'Foto',
  uploading: 'Subiendo {percent}%',
  uploadingLabel: 'Subiendo foto, {percent} por ciento',
  photoFailed: 'No se pudo abrir esa foto. Intenta de nuevo.',
  tapToView: 'Toca para ver',
  photoHiddenLabel:
    'Foto de {name}, oculta porque todavía no se conocen. Toca dos veces para verla.',
  viewPhoto: 'Ver foto',
  closePhoto: 'Cerrar foto',
  reportMessage: 'Reportar mensaje',
  messageOptions: 'Opciones del mensaje',
};

const meetup: Strings['meetup'] = {
  planTitle: 'Planea la entrega',
  spotsTitle: 'Puntos de encuentro',
  police: 'Designado por la policía',
  directions: 'Cómo llegar a {name}',
  directionsShort: 'Cómo llegar',
  somewhereElse: 'Otro lugar',
  customLabel: 'Lugar',
  customPlaceholder: 'Por ejemplo, el lobby de Morrill Tower',
  dayTitle: 'Día',
  timeTitle: 'Hora',
  today: 'Hoy',
  tomorrow: 'Mañana',
  suggest: 'Proponer esta hora',
  accept: 'Aceptar',
  suggestAnother: 'Proponer otra',
  theySuggested: '{name} propuso {when} en {place}',
  youSuggested: 'Propusiste {when} en {place}. Esperando a {name}.',
  noSpots: 'Todavía no hay Puntos de encuentro aquí. Escribe un lugar público.',
  cardProposed: 'Propuesto: {when}',
  cardConfirmed: 'Encuentro confirmado: {when}',
  cardCancelled: 'Encuentro cancelado',
  cardDone: 'Encuentro hecho',
  cardNoShow: 'Marcado como que no llegó',
  open: 'Abrir encuentro',
  dayScreenTitle: 'Encuentro',
  startsIn: 'Empieza en {time}',
  startedAgo: 'Empezó hace {time}',
  minutes: '{n} min',
  hoursMinutes: '{h} h {m} min',
  imHere: 'Ya llegué',
  youreHere: 'Ya llegaste',
  theyreHere: '{name} ya llegó',
  notHereYet: '{name} todavía no avisa que llegó',
  runningLate: 'Voy tarde',
  lateBy: '{n} min',
  youAreLate: 'Les avisaste que llegas {n} min tarde',
  theyAreLate: '{name} llega {n} min tarde',
  cancel: 'Cancelar encuentro',
  cancelTitle: '¿Cancelar este encuentro?',
  cancelBody: 'Le avisaremos a {name}. Pueden planear otra hora en el chat.',
  cancelConfirm: 'Cancelar encuentro',
  keep: 'Mantenerlo',
  reschedule: 'Elegir otra hora',
  share: 'Compartir con un amigo',
  shareMessage: 'Voy a verme con alguien de OnlySwap. Mira dónde y cuándo: {url}',
  noShow: 'No llegó',
  noShowTitle: '¿Reportar que no llegó?',
  noShowBody: 'Úsalo solo si estuviste ahí y nunca llegó. Puede apelar.',
  noShowConfirm: 'Reportar que no llegó',
  noShowSent: 'Gracias. Lo revisaremos.',
  emergency: 'Llamar al 911',
  emergencyHint: 'Si en algún momento te sientes en peligro, vete y llama al 911.',
  cancelled: 'Este encuentro se canceló.',
  rescheduledFrom: 'Cambiado de {when}',
  widgetTitle: 'Próximo encuentro',
  widgetEmpty: 'No hay encuentros planeados',
  widgetEmptyBody: 'Planea uno en un chat.',
  widgetOpenChat: 'Abrir chat',
  widgetWith: 'Con {name}',
  liveTitle: 'Encuentro con {name}',
  liveTitleNoName: 'Tu encuentro',
  liveOnMyWay: 'Voy en camino',
  liveLate: 'Llego {n} min tarde',
  liveStarted: 'Empieza ahora',
};

const deal: Strings['deal'] = {
  didItSellTitle: '¿Se vendió?',
  didYouGetItTitle: '¿Lo recibiste?',
  done: 'Sí, todo listo',
  notYet: 'Todavía no',
  fellThrough: 'No se hizo',
  fellThroughTitle: '¿Cerrar este trato?',
  fellThroughBody: 'El chat se cierra y la publicación vuelve a estar arriba.',
  fellThroughConfirm: 'Cerrar trato',
  markSoldTitle: '¿Quién lo compró?',
  markSoldBody: 'Elige a quien compró para que se califiquen. Los otros chats se cierran.',
  someoneElse: 'Alguien que no está en OnlySwap',
  markSold: 'Marcar vendido',
  rateTitle: 'Califica el intercambio',
  rateQuestion: '¿Qué tal el intercambio con {name}?',
  thumbsUp: 'Bien',
  thumbsDown: 'No tan bien',
  tagsLabel: '¿Qué destacó? (opcional)',
  tags: {
    on_time: 'Puntual',
    as_described: 'Como se describió',
    friendly: 'Amable',
    easy: 'Fácil de tratar',
    late: 'Llegó tarde',
    not_as_described: 'No era como se describió',
    rude: 'Grosero',
    no_show: 'No llegó',
  },
  commentLabel: 'Agrega un comentario (opcional)',
  commentPlaceholder: 'Ejemplo: entrega rápida y fácil',
  submit: 'Enviar calificación',
  waitingTitle: 'Gracias por calificar',
  waitingBody: 'Su calificación aparece cuando también califique, o después de 7 días.',
  revealedTitle: 'Sus calificaciones',
  theirRating: '{name} dijo',
  youSaid: 'Tú dijiste',
  done_: 'Listo',
};

const notificationsScreen: Strings['notificationsScreen'] = {
  title: 'Notificaciones',
  open: 'Notificaciones',
  openUnread: 'Notificaciones, {n} sin leer',
  markAll: 'Marcar todo como leído',
  today: 'Hoy',
  yesterday: 'Ayer',
  earlier: 'Antes',
  emptyTitle: 'Todavía no hay notificaciones',
  emptyBody: 'Aquí aparecen ofertas, mensajes y novedades de encuentros.',
  unread: 'Sin leer',
  settingsTitle: 'Notificaciones',
  osOff: 'Las notificaciones de OnlySwap están desactivadas en los ajustes de tu teléfono.',
  openSettings: 'Abrir ajustes',
  offers: 'Ofertas',
  offersBody: 'Ofertas nuevas, contraofertas y respuestas',
  messages: 'Mensajes',
  messagesBody: 'Mensajes nuevos en chats',
  meetups: 'Encuentros',
  meetupsBody: 'Propuestas, recordatorios y cambios',
  savedSearch: 'Búsquedas guardadas',
  savedSearchBody: 'Resultados nuevos y artículos que dejan de estar apartados',
  priceDrop: 'Bajas de precio',
  priceDropBody: 'Cuando algo que guardaste baja de precio',
  tips: 'Consejos para vender',
  tipsBody:
    'Recordatorios de vez en cuando, como cuando una publicación no recibe ofertas. Son promocionales y están apagados a menos que los actives.',
  quadReplies: 'Respuestas en el Quad',
  quadRepliesBody:
    'Respuestas y logros en tus publicaciones del Quad. Apagado a menos que lo actives.',
  freeFood: 'Comida gratis cerca',
  freeFoodBody:
    'Cuando alguien publica comida gratis en tu campus, hasta 3 al día. Apagado a menos que lo actives.',
  previews: 'Mostrar texto del mensaje',
  previewsBody:
    'Apagado por defecto. Si lo activas, un aviso puede mostrar lo que alguien escribió.',
  quiet: 'Horas de silencio',
  quietBody:
    'Sin avisos de {start} a {end}, salvo recordatorios de encuentros y novedades urgentes.',
  quietStart: 'Inicio',
  quietEnd: 'Fin',
  saveFailed: 'No se pudo guardar. Intenta de nuevo.',
};

const safety: Strings['safety'] = {
  statusTitle: {
    paused: 'Tu cuenta está en pausa',
    suspended: 'Tu cuenta está suspendida',
    banned: 'Tu cuenta está cerrada',
  },
  statusBody: {
    paused:
      'Todavía puedes leer y terminar tus chats abiertos. Las ofertas y publicaciones nuevas están apagadas hasta el {until}.',
    pausedNoDate:
      'Todavía puedes leer y terminar tus chats abiertos. Las ofertas y publicaciones nuevas están apagadas por ahora.',
    suspended:
      'Un moderador suspendió tu cuenta después de un reporte. Puedes apelar una vez y una persona lo revisa.',
    banned: 'Esta cuenta rompió las reglas de una forma que termina el acceso a OnlySwap.',
  },
  reasons: {
    noshow: 'Encuentros a los que no llegaste',
    strike: 'Se rompió una regla',
    report: 'Se confirmó un reporte',
  },
  strikesTitle: 'Faltas',
  noshowsTitle: 'No llegaste',
  openChats: 'Abrir mis chats',
  appeal: 'Apelar',
  appealed: 'Apelación enviada. Una persona la revisará.',
  appealDecided: {
    upheld: 'Revisamos tu apelación. La decisión se mantiene.',
    overturned: 'Tu apelación fue aceptada.',
  },
  signOut: 'Cerrar sesión',
  contact: 'Contactar a soporte',
  appealTitle: 'Apelar',
  appealReasons: {
    mistake: 'Yo no hice esto',
    context: 'Hay más contexto',
    other: 'Otra cosa',
  },
  appealBody: 'Cuéntanos qué pasó',
  appealPlaceholder: 'Cíñete a los hechos. Una persona lee cada apelación.',
  appealSend: 'Enviar apelación',
  reportTitle: 'Tu reporte',
  reportReceived: 'Recibido',
  reportReviewed: 'Revisado',
  reportReceivedBody:
    'Recibimos tu reporte. Una persona lo revisa, normalmente en menos de un día.',
  reportReviewedBody:
    'Revisamos tu reporte y tomamos la acción que nos pareció correcta. No compartimos detalles para proteger la privacidad de todos.',
  blockedTitle: 'Cuentas bloqueadas',
  blockedEmptyTitle: 'No has bloqueado a nadie',
  blockedEmptyBody:
    'Aquí aparecen las personas que bloqueas. Puedes desbloquearlas cuando quieras.',
  unblock: 'Desbloquear',
  unblockName: 'Desbloquear a {name}',
  centerTitle: 'Seguridad',
  spotsTitle: 'Puntos de encuentro',
  spotsBody: 'Lugares públicos del campus. Los designados por la policía están marcados.',
  police: 'Designado por la policía',
  directions: 'Cómo llegar a {name}',
  tipsTitle: 'Antes de verse',
  tips: [
    'Véanse en un Punto de encuentro de día.',
    'Dile a alguien a dónde vas. Puedes compartir tu encuentro desde la app.',
    'Revisa el artículo antes de pagar.',
    'Paga en persona. Nunca pagues antes de verse y nunca mandes un depósito.',
    'Si algo se siente raro, vete. Puedes cancelar cuando quieras.',
  ],
  emergency: 'Llamar al 911',
  emergencyBody: 'Si estás en peligro, llama al 911 de inmediato.',
  bannedTitle: 'Artículos prohibidos',
  bannedIntro: 'Esto no se puede publicar en OnlySwap:',
  banned: [
    'Alcohol, vapes, nicotina y marihuana',
    'Medicamentos, suplementos y drogas',
    'Armas, incluidos gas pimienta y cuchillos',
    'Identificaciones falsas, imitaciones y falsificaciones',
    'Boletos, comidas del plan y permisos de estacionamiento',
    'Tareas, exámenes y ensayos',
    'Mascotas y animales',
    'Tarjetas de regalo y transferencias de dinero',
    'Artículos retirados del mercado o peligrosos',
    'Artículos robados',
  ],
  helpTitle: 'Ayuda',
  faqTitle: 'Preguntas frecuentes',
  faq: [
    {
      q: '¿Cómo pago?',
      a: 'En persona, cuando se vean. En efectivo o con la app que acuerden. OnlySwap nunca maneja dinero.',
    },
    {
      q: '¿Quién puede ver mis publicaciones?',
      a: 'Solo estudiantes verificados de tu universidad. No las ven las personas que bloqueas ni las que te bloquean.',
    },
    {
      q: '¿Y si alguien no llega?',
      a: 'Abre el encuentro y reporta que no llegó después de 20 minutos. Debes haber avisado que llegaste.',
    },
    {
      q: '¿Cómo borro mi cuenta?',
      a: 'Ajustes y luego Borrar cuenta. Tus publicaciones y tu perfil se quitan de inmediato.',
    },
    {
      q: '¿Por qué tengo que confirmar otra vez mi correo universitario?',
      a: 'Una vez al año revisamos que sigas estudiando, para que aquí todos sean estudiantes.',
    },
    {
      q: 'Alguien me está incomodando. ¿Qué hago?',
      a: 'Bloquéalo desde su perfil o el chat y repórtalo. Una persona real revisa cada reporte.',
    },
  ],
  contactTitle: 'Contáctanos',
  contactTopic: 'Tema',
  topics: { general: 'Pregunta', safety: 'Seguridad', bug: 'Algo no funciona', other: 'Otro' },
  contactEmail: 'Tu correo',
  contactBody: 'Mensaje',
  contactSend: 'Enviar',
  contactSent: 'Gracias. Te responderemos por correo.',
  deleteTitle: 'Borrar cuenta',
  deleteBody:
    'Esto quita tu perfil, publicaciones y guardados para siempre. Las personas con las que chateaste verán un usuario eliminado. No se puede deshacer.',
  deleteType: 'Escribe DELETE para confirmar',
  deleteButton: 'Borrar mi cuenta',
  deleteFailed: 'No pudimos borrar tu cuenta. Intenta de nuevo o contacta a soporte.',
};

const me: Strings['me'] = {
  title: 'Perfil',
  verifiedAt: 'Verificado en {campus}',
  statsActive: '{n} publicados',
  statsSold: '{n} vendidos',
  statsSwaps: '{n} intercambios',
  sellNudgeTitle: '¿Tienes algo para vender?',
  sellNudgeBody: 'Toma un minuto. La mayoría de las cosas recibe una oferta la misma semana.',
  sellNudge: 'Publicar algo',
  viewProfile: 'Ver mi perfil público',
  myListings: 'Mis publicaciones',
  saved: 'Guardados',
  notifications: 'Notificaciones',
  settings: 'Ajustes',
  safety: 'Seguridad',
  help: 'Ayuda',
  edit: 'Editar perfil',
  editTitle: 'Editar perfil',
  firstName: 'Nombre',
  lastInitial: 'Inicial del apellido',
  year: 'Año',
  bio: 'Sobre ti (opcional)',
  bioPlaceholder: 'Ejemplo: tercer año, vive en el campus norte',
  changePhoto: 'Cambiar foto',
  uploading: 'Subiendo foto',
  save: 'Guardar',
  saved_: 'Guardado',
  listingsTitle: 'Mis publicaciones',
  tabs: { active: 'Activas', sold: 'Vendidas', other: 'Otras' },
  listingsEmptyTitle: 'Todavía no hay nada publicado',
  listingsEmptyBody: 'Aquí aparecen tus publicaciones.',
  statusLabels: {
    active: 'Activa',
    hold: 'Apartada',
    sold: 'Vendida',
    expired: 'Vencida',
    held_review: 'En revisión',
    removed: 'Quitada',
  },
  relist: 'Republicar',
  stats: 'Estadísticas',
  statsTitle: 'Estadísticas',
  views: 'Vistas',
  saves: 'Guardados',
  offers: 'Ofertas',
  openOffers: 'Ofertas abiertas',
  bestOffer: 'Mejor oferta abierta',
  listed: 'Publicada el {date}',
  expires: 'Vence el {date}',
  priceHistory: 'Cambios de precio',
  noPriceChanges: 'Todavía no hay cambios de precio',
  editListingTitle: 'Editar publicación',
  titleLabel: 'Título',
  descriptionLabel: 'Descripción',
  priceLabel: 'Precio',
  openToOffers: 'Acepto ofertas',
  saveChanges: 'Guardar cambios',
  deleteListing: 'Borrar publicación',
  deleteTitle: '¿Borrar esta publicación?',
  deleteBody: 'Desaparece para todos. Las ofertas abiertas se rechazan y los chats se cierran.',
  deleteConfirm: 'Borrar publicación',
  relistTitle: 'Republicar',
  relistBody: 'Tu publicación vuelve arriba del mazo por 60 días.',
  relistPrice: 'Precio nuevo (opcional)',
  relistButton: 'Republicar',
  relisted: 'Republicada',
};

const legal: Strings['legal'] = {
  version: 'Versión {version}',
  missing: 'No encontramos esa página',
  back: 'Volver',
};

const settings: Strings['settings'] = {
  title: 'Ajustes',
  account: 'Cuenta',
  notifications: 'Notificaciones',
  privacy: 'Privacidad',
  appearance: 'Apariencia',
  language: 'Idioma',
  school: 'Cambiar correo universitario',
  blocked: 'Cuentas bloqueadas',
  data: 'Descargar tus datos',
  about: 'Acerca de',
  signOut: 'Cerrar sesión',
  signOutAll: 'Cerrar sesión en todos los dispositivos',
  signOutAllTitle: '¿Cerrar sesión en todos lados?',
  signOutAllBody: 'Se cierra la sesión en cada teléfono con esta cuenta, incluido este.',
  signOutAllConfirm: 'Cerrar en todos lados',
  deleteAccount: 'Borrar cuenta',
  privacyTitle: 'Privacidad',
  analytics: 'Compartir estadísticas de uso',
  analyticsBody:
    'Conteos anónimos que nos ayudan a arreglar lo que confunde. Nunca tus mensajes ni publicaciones.',
  crash: 'Enviar reportes de fallos',
  crashBody: 'Cuando la app falla, envía un reporte sin tu nombre ni tu correo.',
  appearanceTitle: 'Apariencia',
  modes: { system: 'Igual que el teléfono', light: 'Claro', dark: 'Oscuro' },
  appIconTitle: 'Ícono de la app',
  appIcons: { default: 'Predeterminado', night: 'Noche', paper: 'Papel', mono: 'Mono' },
  appIconFailed: 'No se pudo cambiar el ícono. Inténtalo de nuevo.',
  appIconAndroid: 'Tu pantalla de inicio puede tardar un momento en mostrar el ícono nuevo.',
  lockScreenTitle: 'Pantalla bloqueada',
  liveActivities: 'Mostrar encuentros en la pantalla bloqueada',
  liveActivitiesBody:
    'Una cuenta regresiva empieza 2 horas antes de un encuentro confirmado y termina después. Muestra el lugar, la hora y un nombre de pila.',
  languageTitle: 'Idioma',
  languages: { system: 'Igual que el teléfono', en: 'English', es: 'Español' },
  languageRestartTitle: '¿Cambiar el idioma?',
  languageRestartBody: 'La app se reiniciará para cambiar el idioma.',
  languageRestartConfirm: 'Reiniciar',
  schoolTitle: 'Cambiar correo universitario',
  schoolBody:
    '¿Cambias de correo universitario? Enviaremos un código a la nueva dirección. Tu cuenta y tus publicaciones se quedan.',
  schoolEmail: 'Nuevo correo universitario',
  schoolSend: 'Enviar código',
  schoolSent: 'Revisa {email} para ver un enlace o código que confirme el cambio.',
  aboutTitle: 'Acerca de',
  version: 'Versión {version}',
  terms: 'Términos',
  privacyPolicy: 'Aviso de privacidad',
  rules: 'Reglas de la comunidad',
  licenses: 'Licencias de código abierto',
  licensesBody:
    'OnlySwap está hecho con software de código abierto como React Native, Expo, Supabase y otros, cada uno con su propia licencia.',
  contact: 'Contáctanos',
  dataTitle: 'Descargar tus datos',
  dataIntro:
    'Ponemos una copia de los datos de tu cuenta en un archivo y te enviamos un enlace por correo. El enlace funciona por 7 días.',
  dataIncludesTitle: 'Qué incluye',
  dataIncludes: [
    'Tu perfil y tus ajustes',
    'Tus publicaciones y sus fotos',
    'Ofertas que hiciste y recibiste',
    'Tus chats y mensajes',
    'Calificaciones, guardados y búsquedas guardadas',
    'Bloqueos, reportes y notificaciones',
    'Tus publicaciones y respuestas del Quad',
  ],
  dataOthers: 'Las demás personas aparecen solo con su nombre visible.',
  dataOncePerDay: 'Puedes pedirlo una vez al día.',
  dataButton: 'Enviarme mis datos',
  dataSentTitle: 'En camino',
  dataSent: 'Revisa tu correo universitario en unos minutos. El enlace funciona por 7 días.',
  dataRateLimited: 'Ya lo pediste en el último día. Puedes pedirlo otra vez después de {time}.',
  dataOffline: 'No tienes conexión. Conéctate para pedir tus datos.',
};

const system: Strings['system'] = {
  updateTitle: 'Hora de actualizar',
  updateBody:
    'Esta versión de OnlySwap es muy vieja para seguir funcionando. Actualiza para seguir intercambiando.',
  updateButton: 'Actualizar OnlySwap',
  maintenanceTitle: 'Volvemos enseguida',
  maintenanceBody: 'Estamos haciendo mejoras en OnlySwap.',
  maintenanceUntil: 'Volvemos cerca de las {time}.',
  tryAgain: 'Reintentar',
  linkErrorTitle: 'Ese enlace no funcionó',
  linkErrorBody:
    'Puede ser viejo o estar mal copiado. También puede que la publicación ya no esté.',
  notFoundTitle: 'Aquí no hay nada',
  notFoundBody: 'No encontramos esa página en la app.',
  goHome: 'Ir a Explorar',
  underReview: 'Un moderador está revisando tu publicación. Los demás la verán cuando se apruebe.',
};

const quad: Strings['quad'] = {
  title: 'El Quad',
  subtitle: 'Anónimo para estudiantes',
  sortLabel: 'Ordenar publicaciones',
  sorts: { hot: 'Popular', new: 'Nuevo', top: 'Top' },
  newPost: 'Nueva publicación',
  openActivity: 'Actividad del Quad',
  openMine: 'Tu Quad',
  openMuted: 'Silenciados y ocultos',
  welcomeTitle: 'Dilo sin tu nombre',
  welcomeIntro: 'El Quad es el muro anónimo de tu campus. Cuatro cosas que debes saber primero.',
  ruleAnonTitle: 'Anónimo para estudiantes, no para nosotros',
  ruleAnonBody:
    'Aquí nadie ve quién eres. Guardamos tu cuenta y solo la compartimos si la ley lo exige o si alguien está en peligro.',
  ruleNamesTitle: 'No expongas a estudiantes',
  ruleNamesBody:
    'Nada de nombres, iniciales, fotos ni cuartos de estudiantes en forma negativa. Con los profes sí se vale.',
  ruleHarmTitle: 'Nada de amenazas, odio ni acoso',
  ruleHarmBody: 'Esto se quita y puede cerrar tu cuenta, en el Quad y en el marketplace.',
  ruleVotesTitle: 'Los votos negativos cuentan',
  ruleVotesBody: 'Si una publicación baja a -5, desaparece y la revisamos.',
  agree: 'Acepto las reglas del Quad',
  enter: 'Entrar al Quad',
  emptyTitle: 'Nadie ha publicado todavía',
  emptyBody: 'Empieza tú. Algunas ideas:',
  prompts: [
    '¿Cuál es el mejor lugar para estudiar?',
    '¿La mejor comida de noche cerca del campus?',
    '¿Qué clase debería tomar todo el mundo?',
  ],
  emptyAction: 'Escribe la primera publicación',
  topEmptyTitle: 'No hay publicaciones top esta semana',
  topEmptyBody: 'Vota en Popular y Nuevo y las mejores llegan aquí.',
  offTitle: 'El Quad todavía no está en tu universidad',
  offBody: 'Se abre campus por campus. Todo lo demás en OnlySwap funciona igual.',
  offAction: 'Ir a Explorar',
  pinned: 'Fijada',
  reply1: '1 respuesta',
  replies: '{n} respuestas',
  points: '{n} puntos',
  point1: '1 punto',
  upvote: 'Votar a favor',
  downvote: 'Votar en contra',
  voteLabel: '{action}, {points}',
  ownScore: 'Tu publicación, {points}',
  ownReplyScore: 'Tu respuesta, {points}',
  underReview: 'En revisión',
  options: 'Opciones de la publicación',
  replyOptions: 'Opciones de la respuesta',
  photoLabel: 'Foto de la publicación',
  checkinAt: 'En {place}',
  endsIn: 'Termina en {h} h {m} min',
  endsInMin: 'Termina en {m} min',
  pollVotes: '{n} votos',
  pollVote1: '1 voto',
  pollOption: '{label}, {pct} por ciento',
  pollMine: 'Tu voto',
  pollVoteHint: 'Vota por esta opción',
  voteFailed: 'Tu voto no se registró. Intenta de nuevo.',
  hideAuthor: 'Ocultar publicaciones de esta persona',
  repliesOff: 'Desactivar respuestas',
  repliesOn: 'Activar respuestas',
  deletePost: 'Borrar publicación',
  copyText: 'Copiar texto',
  reportPost: 'Reportar publicación',
  reportReply: 'Reportar respuesta',
  copied: 'Copiado',
  hiddenToast: 'Oculto. No verás sus publicaciones ni respuestas.',
  deleteTitle: '¿Borrar esta publicación?',
  deleteBody: 'Se quita del Quad para todos. No se puede deshacer.',
  deleted: 'Publicación borrada',
  repliesTurnedOff: 'Respuestas desactivadas',
  repliesTurnedOn: 'Respuestas activadas',
  actionFailed: 'Eso no funcionó. Intenta de nuevo.',
  threadTitle: 'Publicación',
  unavailableTitle: 'Esta publicación no está disponible',
  unavailableBody: 'Puede que la hayan quitado, ocultado o borrado.',
  backToQuad: 'Volver al Quad',
  op: 'OP',
  anon: 'Anón {letter}',
  opLabel: 'Autor original',
  you: 'Tú',
  repliesOffNote: 'El autor desactivó las respuestas.',
  noReplies: 'Todavía no hay respuestas.',
  replyLabel: 'Responder en anónimo',
  replyPlaceholder: 'Agrega una respuesta',
  sendReply: 'Enviar respuesta',
  replyHeld: 'Tu respuesta espera una revisión rápida.',
  newTitle: 'Nueva publicación',
  post: 'Publicar',
  modeLabel: 'Tipo de publicación',
  modes: { text: 'Texto', photo: 'Foto', poll: 'Encuesta', checkin: 'Check-in' },
  bodyLabel: '¿Qué tienes en mente?',
  bodyPlaceholder: 'No pongas nombres de estudiantes',
  anonNote: 'Publicas en anónimo',
  addPhoto: 'Agregar foto',
  changePhoto: 'Cambiar foto',
  removePhoto: 'Quitar foto',
  photoUploading: 'Subiendo foto',
  photoFailed: 'La foto no se subió. Intenta de nuevo.',
  photosOff: 'Las fotos están desactivadas para OnlySwap. Actívalas en Ajustes para agregar una.',
  openSettings: 'Abrir Ajustes',
  pollQuestionLabel: 'Tu pregunta',
  pollOptionLabel: 'Opción {n}',
  addOption: 'Agregar opción',
  removeOption: 'Quitar opción {n}',
  pollHint: 'De 2 a 4 opciones, hasta 40 caracteres cada una.',
  placeLabel: '¿Dónde estás?',
  placePlaceholder: 'Biblioteca, 3er piso',
  vibesLabel: 'Ambiente',
  vibes: { quiet: 'Tranquilo', busy: 'Lleno', studying: 'Estudiando', hanging: 'Pasando el rato' },
  checkinNoteLabel: '¿Algo que agregar? (opcional)',
  checkinHint: 'Los check-ins desaparecen después de 3 horas.',
  posted: 'Publicado en el Quad',
  blockedTitle: 'Esto no puede ir en el Quad',
  blocked: {
    phone:
      'Tiene un número de teléfono. Los números, correos y números de cuarto no van en el Quad para que nadie pueda ser localizado.',
    email:
      'Tiene un correo. Los números, correos y números de cuarto no van en el Quad para que nadie pueda ser localizado.',
    url: 'Tiene un enlace. Los enlaces a otras apps y sitios no van en el Quad.',
    handle:
      'Tiene un usuario de redes sociales. Los usuarios no van en el Quad para que nadie pueda ser localizado.',
    room: 'Tiene un número de cuarto. Los números, correos y números de cuarto no van en el Quad para que nadie pueda ser localizado.',
    term: 'Usa "{term}", que no se permite en el Quad.',
    other: 'Algo de esto no se permite en el Quad.',
  },
  listingHint:
    '¿Vendes algo? Mejor súbelo como publicación. Quien compra te puede escribir ahí sin ver tu número.',
  editPost: 'Editar publicación',
  makeListing: 'Hacerlo publicación',
  heldTitle: 'Enviado a revisión',
  held: {
    names_student:
      'Esto podría nombrar a un estudiante. Lo que expone a estudiantes lo revisa una persona primero, aunque sea broma. Mejor prueba con "alguien del 7.º piso".',
    term: 'Tiene una palabra que revisamos a mano. Una persona la revisa antes de que aparezca.',
    new_account_photo:
      'Las fotos de cuentas nuevas se revisan primero. Aparece cuando una persona la revise.',
    other: 'Una persona lo revisa antes de que aparezca.',
  },
  heldNote: 'Lo encuentras en Tu Quad mientras espera.',
  mineTitle: 'Tu Quad',
  onlyYou: 'Solo tú puedes ver esto.',
  minePosts: 'Publicaciones',
  mineReplies: 'Respuestas',
  mineEmptyPosts: 'Todavía no publicas nada',
  mineEmptyReplies: 'Todavía no respondes a nada',
  status: {
    live: 'Publicada',
    held: 'En revisión',
    hidden: 'Oculta por votos',
    removed: 'Quitada',
  },
  onPost: 'En: {excerpt}',
  appeal: 'Apelar',
  appealed: 'Apelación enviada. Una persona la revisará.',
  activityTitle: 'Actividad del Quad',
  activityEmptyTitle: 'Nada todavía',
  activityEmptyBody: 'Aquí aparecen las respuestas y logros de tus publicaciones.',
  mutedTitle: 'Silenciados y ocultos',
  hiddenPeople: 'Personas que ocultaste',
  hiddenFrom: 'Alguien que ocultaste, de: "{excerpt}"',
  unhide: 'Mostrar',
  unhideLabel: 'Volver a mostrar a alguien que ocultaste de "{excerpt}"',
  noHidden: 'No has ocultado a nadie.',
  keywords: 'Palabras silenciadas',
  keywordsBody: 'Las publicaciones y respuestas con estas palabras se ocultan para ti.',
  keywordLabel: 'Silenciar una palabra',
  keywordPlaceholder: 'finales',
  addKeyword: 'Silenciar',
  removeKeyword: 'Quitar',
  keywordInvalid: 'Usa de 2 a 30 caracteres.',
  noKeywords: 'No hay palabras silenciadas.',
};

const campus: Strings['campus'] = {
  segmentLabel: 'Vista de Explorar',
  segmentSwipe: 'Deslizar',
  segmentCampus: 'En el campus',
  title: 'En el campus',
  filtersLabel: 'Mostrar',
  filters: {
    all: 'Todo',
    food: 'Comida gratis',
    free: 'Cosas gratis',
    wanted: 'Se busca',
    new: 'Nuevo',
  },
  loading: 'Cargando publicaciones',
  postFood: 'Publicar comida gratis',
  askFor: 'Pedir algo',
  foodTag: 'Comida gratis',
  freeTag: 'Gratis',
  wantedTag: 'Se busca',
  upTo: 'Hasta {price}',
  anyBudget: 'Cualquier presupuesto',
  minutesLeft: 'Quedan {n} min',
  hoursLeft: 'Quedan {h} h {m} min',
  hoursOnly: 'Quedan {h} h',
  underMinute: 'Queda menos de un minuto',
  gone: 'Se acabó',
  goneBody: 'Se acabó el tiempo de esta.',
  noPlace: 'Pregunta el lugar en la publicación',
  iHaveThis: 'Yo lo tengo',
  iHaveThisLabel: 'Yo lo tengo: publicar {title} para esa persona',
  yours: 'Tu publicación',
  foodLabel: 'Comida gratis: {title}. {place}. {time}',
  wantedLabel: 'Se busca: {title}. {budget}. {who}',
  listingLabel: '{title}, {price}. {meta}',
  byLine: '{name} · {ago}',
  loadingMore: 'Cargando más',
  empty: {
    all: {
      title: 'Todo tranquilo en el campus por ahora',
      body: 'Aquí aparecen comida gratis, regalos, publicaciones de Se busca y publicaciones nuevas.',
    },
    food: {
      title: 'No hay comida gratis ahora',
      body: 'Activa las alertas de comida gratis en los ajustes de notificaciones para enterarte primero.',
    },
    free: {
      title: 'No hay nada gratis ahora',
      body: 'Los regalos normalmente se van en un día. Vuelve más tarde.',
    },
    wanted: {
      title: 'Todavía no hay publicaciones de Se busca',
      body: '¿Necesitas algo? Pídelo y quien lo tenga lo puede publicar para ti.',
    },
    new: {
      title: 'Nada nuevo esta semana',
      body: 'Aquí aparecen las publicaciones de los últimos 7 días.',
    },
  },
  dayOneTitle: 'Esto apenas empieza',
  dayOneBody: '{n} publicaciones hasta ahora. Publica lo tuyo y sé de los primeros.',
  dayOneBodyOne: '1 publicación hasta ahora. Publica lo tuyo y sé de los primeros.',
  dayOneBodyNone: 'Todavía no hay nada publicado. Publica lo primero.',
  dayOneAction: 'Publicar algo',
  foundingTitle: 'Hay lugares de vendedor fundador',
  foundingBody:
    'Quedan {left} de {limit} lugares. Los primeros vendedores aquí se quedan con una insignia para siempre.',
  foundingMineTitle: 'Eres vendedor fundador',
  foundingMineBody: 'Tu insignia aparece en tu perfil. Regalar cosas también cuenta.',
  foundingAction: 'Publicar algo',
  foodTitle: 'Publicar comida gratis',
  foodWhat: '¿Qué es?',
  foodWhatPlaceholder: 'Por ejemplo, pizza que sobró de una reunión de club',
  foodWhere: '¿Dónde exactamente?',
  foodWhereBody: 'Elige un Punto de encuentro o escribe el lugar.',
  foodOther: 'Otro lugar',
  foodOtherPlaceholder: 'Por ejemplo, Dreese Lab, sala del 2.º piso',
  foodFor: 'Disponible por',
  foodMinutes: {
    m30: '30 min',
    m60: '1 hora',
    m120: '2 horas',
    m180: '3 horas',
  },
  foodNote:
    'Las personas del campus con alertas de comida gratis reciben una notificación. La publicación se oculta sola cuando se acaba el tiempo.',
  foodPostedTitle: 'Tu publicación de comida gratis ya está arriba',
  foodPostedBody: 'Aparece en En el campus hasta que se acabe el tiempo.',
  wantedTitle: 'Pedir algo',
  wantedWhat: '¿Qué estás buscando?',
  wantedWhatPlaceholder: 'Por ejemplo, TI-84 Plus para MATH 1151',
  budgetLabel: 'Presupuesto en dólares (opcional)',
  budgetPlaceholder: '40',
  budgetHint: 'Déjalo vacío si eres flexible.',
  categoryLabel: 'Categoría (opcional)',
  categoryHint: 'Quien publique algo en esta categoría se entera de tu publicación.',
  detailsLabel: 'Detalles (opcional)',
  detailsPlaceholder: 'Edición, tamaño, color, para cuándo lo necesitas.',
  wantedNote:
    'Los demás ven tu nombre y presupuesto. Quien lo tenga lo publica y te llega una notificación para que hagas una oferta.',
  wantedPostedTitle: 'Tu publicación de Se busca ya está arriba',
  wantedPostedBody: 'Te avisamos cuando alguien publique uno.',
  reviewTitle: 'Tu publicación está en revisión',
  reviewBody: 'La mayoría de las revisiones toma menos de 2 horas. Te avisamos cuando esté arriba.',
  postedCheck: 'Publicado',
  seeCampus: 'Ver En el campus',
  done: 'Listo',
  post: 'Publicar',
  addPhoto: 'Agregar foto',
  changePhoto: 'Cambiar foto',
  removePhoto: 'Quitar foto',
  photoOptional: 'Foto (opcional)',
  photoUploading: 'Subiendo foto',
  photoFailed: 'La foto no se subió. Intenta de nuevo.',
  photoLabel: 'Tu foto',
  photosOff:
    'El acceso a fotos está desactivado para OnlySwap. Actívalo en Ajustes para agregar una foto.',
  openSettings: 'Abrir ajustes',
  fixFirst: 'Corrige los campos marcados para publicar.',
  errors: {
    titleShort: 'Agrega al menos 3 caracteres.',
    titleLong: 'Usa menos de 80 caracteres.',
    placeMissing: 'Elige un lugar o escribe dónde está.',
    placeLong: 'Usa menos de 60 caracteres en el lugar.',
    minutesRange: 'Elige por cuánto tiempo estará.',
    budgetHigh: 'Los presupuestos llegan hasta $2,000.',
    descriptionLong: 'Usa menos de 1000 caracteres en los detalles.',
    banned: '"{term}" no está permitido en OnlySwap.',
    foodCap:
      'Ya son 3 publicaciones de comida gratis hoy, el máximo por día. Puedes publicar otra vez mañana.',
    wantedCap:
      'Ya son 5 publicaciones de Se busca hoy, el máximo por día. Puedes publicar otra vez mañana.',
    newAccountCap: 'Las cuentas nuevas pueden publicar 3 cosas el primer día. Intenta mañana.',
    dailyCap: 'Ya son 20 publicaciones hoy, el máximo por día. Puedes publicar otra vez mañana.',
    postFailed: 'No pudimos publicarlo. Revisa tu conexión e intenta de nuevo.',
  },
  answeringTitle: 'Respondes a un Se busca',
  answeringBody: '{title}. Al publicar, le llega una notificación y puede hacer una oferta.',
  answeringRemove: 'No es para esta publicación',
  listingFood: 'Comida gratis',
  listingWanted: 'Se busca',
  listingFoodBody: 'Gratis para todos. Ve al lugar mientras haya.',
  listingWantedBody: 'Alguien está buscando esto. ¿Tienes uno? Publícalo para esa persona.',
  wantedOwnBody: 'Te avisamos cuando alguien publique uno.',
};

const waitlist: Strings['waitlist'] = {
  title: 'Lista de espera',
  heading: '{campus} abre con {threshold} estudiantes',
  headingNoCampus: 'Tu universidad abre con {threshold} estudiantes',
  progressLabel: 'Se unieron {members} de {threshold} estudiantes',
  count: '{members} / {threshold}',
  position: 'Eres el número {position}. Cuando se unan {left} personas más, se abre para todos.',
  positionOne: 'Eres el número {position}. Cuando se una 1 persona más, se abre para todos.',
  positionNone: 'Cuando se unan {left} personas más, se abre para todos.',
  almost: 'Ya están todos los que hacían falta. Se abre en cualquier momento.',
  inviteTitle: 'Tu enlace de invitación',
  inviteBody: 'Cada amigo que se une con él acerca la apertura.',
  copyLink: 'Copiar enlace',
  copyLabel: 'Copiar tu enlace de invitación',
  copied: 'Enlace copiado',
  copyFailed: 'No se pudo copiar el enlace. Intenta de nuevo.',
  share: 'Invitar amigos',
  shareMessage: 'Únete a OnlySwap, el marketplace solo para estudiantes de {campus}. {link}',
  shareMessageNoCampus:
    'Únete a OnlySwap, el marketplace solo para estudiantes de nuestra universidad. {link}',
  invitedNone: 'Nadie se ha unido con tu enlace todavía.',
  invitedOne: '1 persona se unió con tu enlace.',
  invited: '{n} personas se unieron con tu enlace.',
  nextTitle: 'Qué sigue',
  next: {
    count: 'Contamos a cada estudiante verificado que se registra.',
    open: 'Al llegar a {threshold}, OnlySwap se abre para todos a la vez.',
    tell: 'Te llega una notificación y puedes empezar a deslizar y vender de inmediato.',
  },
  tourTitle: 'Cómo funciona OnlySwap',
  tour: {
    swipeTitle: 'Desliza',
    swipeBody: 'Mira lo que venden los estudiantes de tu campus.',
    offerTitle: 'Haz una oferta',
    offerBody: 'El chat se abre cuando quien vende acepta.',
    meetTitle: 'Véanse en el campus',
    meetBody: 'Elijan un Punto de encuentro público y paguen en persona.',
  },
  notify: 'Recibir una notificación cuando abra',
  signOut: 'Cerrar sesión',
  loading: 'Cargando tu lugar',
};

const unlocked: Strings['unlocked'] = {
  title: 'Tu campus ya abrió',
  body: '{campus} llegó a {threshold} estudiantes, así que OnlySwap está abierto para todos ahí. Eres de las primeras personas en entrar.',
  bodyNoCampus:
    'Tu universidad llegó a su meta, así que OnlySwap está abierto para todos ahí. Eres de las primeras personas en entrar.',
  foundingTitle: 'Hay lugares de vendedor fundador',
  foundingBody:
    'Los primeros vendedores aquí se quedan con una insignia para siempre. Regalar algo también cuenta.',
  start: 'Empieza a deslizar',
  list: 'Publicar algo',
  label: 'Campus abierto',
};

const spotsMap: Strings['spotsMap'] = {
  show: 'Ver mapa',
  hide: 'Ocultar mapa',
  attribution: 'Mapa: OpenFreeMap, OpenMapTiles. Datos de colaboradores de OpenStreetMap.',
  spike: 'Prueba de mapa (MapLibre + OpenFreeMap)',
  spikeSpot: 'Pin de prueba',
};

const web: Strings['web'] = {
  appName: 'OnlySwap',
  titles: {
    signIn: 'Iniciar sesión',
    discover: 'Explorar',
    search: 'Buscar',
    saved: 'Guardados',
    listing: 'Publicación',
    offer: 'Hacer una oferta',
    inbox: 'Bandeja',
    chat: 'Chat',
    sell: 'Vender',
    profile: 'Perfil',
    settings: 'Ajustes',
    notifications: 'Notificaciones',
    quad: 'Quad',
    meetup: 'Encuentro',
    safety: 'Seguridad',
    help: 'Ayuda',
  },
};

export const es: Strings = {
  permissions,
  tabs,
  shell,
  errors,
  sheet,
  toast,
  banner,
  photo,
  states,
  nav,
  primer,
  report,
  dev,
  kit,
  kit2,
  statesFx,
  launch,
  welcome,
  signIn,
  age,
  profileSetup,
  rules,
  notifyPrimer,
  sessionExpired,
  reverify,
  emailAccess,
  sell,
  feed,
  search,
  saved,
  profileView,
  offers,
  chat,
  meetup,
  deal,
  notificationsScreen,
  safety,
  me,
  settings,
  legal,
  system,
  quad,
  campus,
  waitlist,
  unlocked,
  spotsMap,
  web,
};

export default es;
